package console

type MysqlStubs struct{}

// Jobs Create jobs table migration content.
func (receiver MysqlStubs) Jobs() string {
	return `CREATE TABLE failed_jobs
(
    id         BIGINT AUTO_INCREMENT PRIMARY KEY,
    queue      VARCHAR(255) NOT NULL,
    job        VARCHAR(255) NOT NULL,
    payload    JSON         NOT NULL,
    exception  TEXT         NOT NULL,
    failed_at  TIMESTAMP    NOT NULL
);

CREATE INDEX idx_failed_jobs_failed_at ON failed_jobs (queue, job, failed_at);
`
}

type PostgresqlStubs struct{}

// Jobs Create jobs table migration content.
func (receiver PostgresqlStubs) Jobs() string {
	return `CREATE TABLE failed_jobs
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    queue     TEXT      NOT NULL,
    job       TEXT      NOT NULL,
    payload   JSONB     NOT NULL,
    exception TEXT      NOT NULL,
    failed_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_failed_jobs_failed_at ON failed_jobs (queue, job, failed_at);
`
}

type SqliteStubs struct{}

// Jobs Create jobs table migration content.
func (receiver SqliteStubs) Jobs() string {
	return `CREATE TABLE failed_jobs
(
    id        BIGINT AUTO_INCREMENT PRIMARY KEY,
    queue     TEXT      NOT NULL,
    job       TEXT      NOT NULL,
    payload   JSON      NOT NULL,
    exception TEXT      NOT NULL,
    failed_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_failed_jobs_failed_at ON failed_jobs (queue, job, failed_at);
`
}

type SqlserverStubs struct{}

// Jobs Create jobs table migration content.
func (receiver SqlserverStubs) Jobs() string {
	return `CREATE TABLE failed_jobs
(
    id        BIGINT IDENTITY (1,1) PRIMARY KEY,
    queue     VARCHAR(MAX) NOT NULL,
    job       VARCHAR(MAX) NOT NULL,
    payload   VARCHAR(MAX) NOT NULL,
    exception VARCHAR(MAX) NOT NULL,
    failed_at TIMESTAMP    NOT NULL
);

CREATE INDEX idx_failed_jobs_failed_at ON failed_jobs (queue, job, failed_at);
`
}
