// Code generated by mockery. DO NOT EDIT.

package broadcasting

import mock "github.com/stretchr/testify/mock"

// ChannelAuthFunc is an autogenerated mock type for the ChannelAuthFunc type
type ChannelAuthFunc struct {
	mock.Mock
}

type ChannelAuthFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *ChannelAuthFunc) EXPECT() *ChannelAuthFunc_Expecter {
	return &ChannelAuthFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: user, channelName, params
func (_m *ChannelAuthFunc) Execute(user interface{}, channelName string, params map[string]string) bool {
	ret := _m.Called(user, channelName, params)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(interface{}, string, map[string]string) bool); ok {
		r0 = rf(user, channelName, params)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ChannelAuthFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ChannelAuthFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - user interface{}
//   - channelName string
//   - params map[string]string
func (_e *ChannelAuthFunc_Expecter) Execute(user interface{}, channelName interface{}, params interface{}) *ChannelAuthFunc_Execute_Call {
	return &ChannelAuthFunc_Execute_Call{Call: _e.mock.On("Execute", user, channelName, params)}
}

func (_c *ChannelAuthFunc_Execute_Call) Run(run func(user interface{}, channelName string, params map[string]string)) *ChannelAuthFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].(string), args[2].(map[string]string))
	})
	return _c
}

func (_c *ChannelAuthFunc_Execute_Call) Return(_a0 bool) *ChannelAuthFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChannelAuthFunc_Execute_Call) RunAndReturn(run func(interface{}, string, map[string]string) bool) *ChannelAuthFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewChannelAuthFunc creates a new instance of ChannelAuthFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChannelAuthFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChannelAuthFunc {
	mock := &ChannelAuthFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
