// Code generated by mockery. DO NOT EDIT.

package notification

import (
	notification "github.com/goravel/framework/contracts/notification"
	mock "github.com/stretchr/testify/mock"
)

// Channel is an autogenerated mock type for the Channel type
type Channel struct {
	mock.Mock
}

type Channel_Expecter struct {
	mock *mock.Mock
}

func (_m *Channel) EXPECT() *Channel_Expecter {
	return &Channel_Expecter{mock: &_m.Mock}
}

// Send provides a mock function with given fields: notifiable, notif
func (_m *Channel) Send(notifiable notification.Notifiable, notif interface{}) error {
	ret := _m.Called(notifiable, notif)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(notification.Notifiable, interface{}) error); ok {
		r0 = rf(notifiable, notif)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Channel_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type Channel_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - notifiable notification.Notifiable
//   - notif interface{}
func (_e *Channel_Expecter) Send(notifiable interface{}, notif interface{}) *Channel_Send_Call {
	return &Channel_Send_Call{Call: _e.mock.On("Send", notifiable, notif)}
}

func (_c *Channel_Send_Call) Run(run func(notifiable notification.Notifiable, notif interface{})) *Channel_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(notification.Notifiable), args[1].(interface{}))
	})
	return _c
}

func (_c *Channel_Send_Call) Return(_a0 error) *Channel_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Channel_Send_Call) RunAndReturn(run func(notification.Notifiable, interface{}) error) *Channel_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewChannel creates a new instance of Channel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChannel(t interface {
	mock.TestingT
	Cleanup(func())
}) *Channel {
	mock := &Channel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
