// Code generated by mockery. DO NOT EDIT.

package notification

import (
	notification "github.com/goravel/framework/contracts/notification"
	mock "github.com/stretchr/testify/mock"
)

// DatabaseNotification is an autogenerated mock type for the DatabaseNotification type
type DatabaseNotification struct {
	mock.Mock
}

type DatabaseNotification_Expecter struct {
	mock *mock.Mock
}

func (_m *DatabaseNotification) EXPECT() *DatabaseNotification_Expecter {
	return &DatabaseNotification_Expecter{mock: &_m.Mock}
}

// ID provides a mock function with no fields
func (_m *DatabaseNotification) ID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// DatabaseNotification_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type DatabaseNotification_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *DatabaseNotification_Expecter) ID() *DatabaseNotification_ID_Call {
	return &DatabaseNotification_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *DatabaseNotification_ID_Call) Run(run func()) *DatabaseNotification_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DatabaseNotification_ID_Call) Return(_a0 string) *DatabaseNotification_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DatabaseNotification_ID_Call) RunAndReturn(run func() string) *DatabaseNotification_ID_Call {
	_c.Call.Return(run)
	return _c
}

// ToDatabase provides a mock function with given fields: notifiable
func (_m *DatabaseNotification) ToDatabase(notifiable notification.Notifiable) map[string]interface{} {
	ret := _m.Called(notifiable)

	if len(ret) == 0 {
		panic("no return value specified for ToDatabase")
	}

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func(notification.Notifiable) map[string]interface{}); ok {
		r0 = rf(notifiable)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// DatabaseNotification_ToDatabase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToDatabase'
type DatabaseNotification_ToDatabase_Call struct {
	*mock.Call
}

// ToDatabase is a helper method to define mock.On call
//   - notifiable notification.Notifiable
func (_e *DatabaseNotification_Expecter) ToDatabase(notifiable interface{}) *DatabaseNotification_ToDatabase_Call {
	return &DatabaseNotification_ToDatabase_Call{Call: _e.mock.On("ToDatabase", notifiable)}
}

func (_c *DatabaseNotification_ToDatabase_Call) Run(run func(notifiable notification.Notifiable)) *DatabaseNotification_ToDatabase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(notification.Notifiable))
	})
	return _c
}

func (_c *DatabaseNotification_ToDatabase_Call) Return(_a0 map[string]interface{}) *DatabaseNotification_ToDatabase_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DatabaseNotification_ToDatabase_Call) RunAndReturn(run func(notification.Notifiable) map[string]interface{}) *DatabaseNotification_ToDatabase_Call {
	_c.Call.Return(run)
	return _c
}

// Via provides a mock function with given fields: notifiable
func (_m *DatabaseNotification) Via(notifiable notification.Notifiable) []string {
	ret := _m.Called(notifiable)

	if len(ret) == 0 {
		panic("no return value specified for Via")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func(notification.Notifiable) []string); ok {
		r0 = rf(notifiable)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// DatabaseNotification_Via_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Via'
type DatabaseNotification_Via_Call struct {
	*mock.Call
}

// Via is a helper method to define mock.On call
//   - notifiable notification.Notifiable
func (_e *DatabaseNotification_Expecter) Via(notifiable interface{}) *DatabaseNotification_Via_Call {
	return &DatabaseNotification_Via_Call{Call: _e.mock.On("Via", notifiable)}
}

func (_c *DatabaseNotification_Via_Call) Run(run func(notifiable notification.Notifiable)) *DatabaseNotification_Via_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(notification.Notifiable))
	})
	return _c
}

func (_c *DatabaseNotification_Via_Call) Return(_a0 []string) *DatabaseNotification_Via_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DatabaseNotification_Via_Call) RunAndReturn(run func(notification.Notifiable) []string) *DatabaseNotification_Via_Call {
	_c.Call.Return(run)
	return _c
}

// NewDatabaseNotification creates a new instance of DatabaseNotification. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDatabaseNotification(t interface {
	mock.TestingT
	Cleanup(func())
}) *DatabaseNotification {
	mock := &DatabaseNotification{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
