// Code generated by mockery. DO NOT EDIT.

package notification

import (
	notification "github.com/goravel/framework/contracts/notification"
	mock "github.com/stretchr/testify/mock"
)

// MailableNotification is an autogenerated mock type for the MailableNotification type
type MailableNotification struct {
	mock.Mock
}

type MailableNotification_Expecter struct {
	mock *mock.Mock
}

func (_m *MailableNotification) EXPECT() *MailableNotification_Expecter {
	return &MailableNotification_Expecter{mock: &_m.Mock}
}

// ToMail provides a mock function with given fields: notifiable
func (_m *MailableNotification) ToMail(notifiable notification.Notifiable) notification.MailMessage {
	ret := _m.Called(notifiable)

	if len(ret) == 0 {
		panic("no return value specified for ToMail")
	}

	var r0 notification.MailMessage
	if rf, ok := ret.Get(0).(func(notification.Notifiable) notification.MailMessage); ok {
		r0 = rf(notifiable)
	} else {
		r0 = ret.Get(0).(notification.MailMessage)
	}

	return r0
}

// MailableNotification_ToMail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToMail'
type MailableNotification_ToMail_Call struct {
	*mock.Call
}

// ToMail is a helper method to define mock.On call
//   - notifiable notification.Notifiable
func (_e *MailableNotification_Expecter) ToMail(notifiable interface{}) *MailableNotification_ToMail_Call {
	return &MailableNotification_ToMail_Call{Call: _e.mock.On("ToMail", notifiable)}
}

func (_c *MailableNotification_ToMail_Call) Run(run func(notifiable notification.Notifiable)) *MailableNotification_ToMail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(notification.Notifiable))
	})
	return _c
}

func (_c *MailableNotification_ToMail_Call) Return(_a0 notification.MailMessage) *MailableNotification_ToMail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MailableNotification_ToMail_Call) RunAndReturn(run func(notification.Notifiable) notification.MailMessage) *MailableNotification_ToMail_Call {
	_c.Call.Return(run)
	return _c
}

// Via provides a mock function with given fields: notifiable
func (_m *MailableNotification) Via(notifiable notification.Notifiable) []string {
	ret := _m.Called(notifiable)

	if len(ret) == 0 {
		panic("no return value specified for Via")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func(notification.Notifiable) []string); ok {
		r0 = rf(notifiable)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MailableNotification_Via_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Via'
type MailableNotification_Via_Call struct {
	*mock.Call
}

// Via is a helper method to define mock.On call
//   - notifiable notification.Notifiable
func (_e *MailableNotification_Expecter) Via(notifiable interface{}) *MailableNotification_Via_Call {
	return &MailableNotification_Via_Call{Call: _e.mock.On("Via", notifiable)}
}

func (_c *MailableNotification_Via_Call) Run(run func(notifiable notification.Notifiable)) *MailableNotification_Via_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(notification.Notifiable))
	})
	return _c
}

func (_c *MailableNotification_Via_Call) Return(_a0 []string) *MailableNotification_Via_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MailableNotification_Via_Call) RunAndReturn(run func(notification.Notifiable) []string) *MailableNotification_Via_Call {
	_c.Call.Return(run)
	return _c
}

// NewMailableNotification creates a new instance of MailableNotification. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMailableNotification(t interface {
	mock.TestingT
	Cleanup(func())
}) *MailableNotification {
	mock := &MailableNotification{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
