// Code generated by mockery. DO NOT EDIT.

package notification

import (
	notification "github.com/goravel/framework/contracts/notification"
	mock "github.com/stretchr/testify/mock"
)

// NotificationWithDatabaseConnection is an autogenerated mock type for the NotificationWithDatabaseConnection type
type NotificationWithDatabaseConnection struct {
	mock.Mock
}

type NotificationWithDatabaseConnection_Expecter struct {
	mock *mock.Mock
}

func (_m *NotificationWithDatabaseConnection) EXPECT() *NotificationWithDatabaseConnection_Expecter {
	return &NotificationWithDatabaseConnection_Expecter{mock: &_m.Mock}
}

// DatabaseConnection provides a mock function with no fields
func (_m *NotificationWithDatabaseConnection) DatabaseConnection() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DatabaseConnection")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NotificationWithDatabaseConnection_DatabaseConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DatabaseConnection'
type NotificationWithDatabaseConnection_DatabaseConnection_Call struct {
	*mock.Call
}

// DatabaseConnection is a helper method to define mock.On call
func (_e *NotificationWithDatabaseConnection_Expecter) DatabaseConnection() *NotificationWithDatabaseConnection_DatabaseConnection_Call {
	return &NotificationWithDatabaseConnection_DatabaseConnection_Call{Call: _e.mock.On("DatabaseConnection")}
}

func (_c *NotificationWithDatabaseConnection_DatabaseConnection_Call) Run(run func()) *NotificationWithDatabaseConnection_DatabaseConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *NotificationWithDatabaseConnection_DatabaseConnection_Call) Return(_a0 string) *NotificationWithDatabaseConnection_DatabaseConnection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NotificationWithDatabaseConnection_DatabaseConnection_Call) RunAndReturn(run func() string) *NotificationWithDatabaseConnection_DatabaseConnection_Call {
	_c.Call.Return(run)
	return _c
}

// Via provides a mock function with given fields: notifiable
func (_m *NotificationWithDatabaseConnection) Via(notifiable notification.Notifiable) []string {
	ret := _m.Called(notifiable)

	if len(ret) == 0 {
		panic("no return value specified for Via")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func(notification.Notifiable) []string); ok {
		r0 = rf(notifiable)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// NotificationWithDatabaseConnection_Via_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Via'
type NotificationWithDatabaseConnection_Via_Call struct {
	*mock.Call
}

// Via is a helper method to define mock.On call
//   - notifiable notification.Notifiable
func (_e *NotificationWithDatabaseConnection_Expecter) Via(notifiable interface{}) *NotificationWithDatabaseConnection_Via_Call {
	return &NotificationWithDatabaseConnection_Via_Call{Call: _e.mock.On("Via", notifiable)}
}

func (_c *NotificationWithDatabaseConnection_Via_Call) Run(run func(notifiable notification.Notifiable)) *NotificationWithDatabaseConnection_Via_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(notification.Notifiable))
	})
	return _c
}

func (_c *NotificationWithDatabaseConnection_Via_Call) Return(_a0 []string) *NotificationWithDatabaseConnection_Via_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NotificationWithDatabaseConnection_Via_Call) RunAndReturn(run func(notification.Notifiable) []string) *NotificationWithDatabaseConnection_Via_Call {
	_c.Call.Return(run)
	return _c
}

// NewNotificationWithDatabaseConnection creates a new instance of NotificationWithDatabaseConnection. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationWithDatabaseConnection(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationWithDatabaseConnection {
	mock := &NotificationWithDatabaseConnection{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
