// Code generated by mockery. DO NOT EDIT.

package notification

import (
	time "time"

	notification "github.com/goravel/framework/contracts/notification"
	mock "github.com/stretchr/testify/mock"
)

// NotificationWithBackoff is an autogenerated mock type for the NotificationWithBackoff type
type NotificationWithBackoff struct {
	mock.Mock
}

type NotificationWithBackoff_Expecter struct {
	mock *mock.Mock
}

func (_m *NotificationWithBackoff) EXPECT() *NotificationWithBackoff_Expecter {
	return &NotificationWithBackoff_Expecter{mock: &_m.Mock}
}

// Backoff provides a mock function with given fields: channel
func (_m *NotificationWithBackoff) Backoff(channel string) []time.Duration {
	ret := _m.Called(channel)

	if len(ret) == 0 {
		panic("no return value specified for Backoff")
	}

	var r0 []time.Duration
	if rf, ok := ret.Get(0).(func(string) []time.Duration); ok {
		r0 = rf(channel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]time.Duration)
		}
	}

	return r0
}

// NotificationWithBackoff_Backoff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Backoff'
type NotificationWithBackoff_Backoff_Call struct {
	*mock.Call
}

// Backoff is a helper method to define mock.On call
//   - channel string
func (_e *NotificationWithBackoff_Expecter) Backoff(channel interface{}) *NotificationWithBackoff_Backoff_Call {
	return &NotificationWithBackoff_Backoff_Call{Call: _e.mock.On("Backoff", channel)}
}

func (_c *NotificationWithBackoff_Backoff_Call) Run(run func(channel string)) *NotificationWithBackoff_Backoff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *NotificationWithBackoff_Backoff_Call) Return(_a0 []time.Duration) *NotificationWithBackoff_Backoff_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NotificationWithBackoff_Backoff_Call) RunAndReturn(run func(string) []time.Duration) *NotificationWithBackoff_Backoff_Call {
	_c.Call.Return(run)
	return _c
}

// Via provides a mock function with given fields: notifiable
func (_m *NotificationWithBackoff) Via(notifiable notification.Notifiable) []string {
	ret := _m.Called(notifiable)

	if len(ret) == 0 {
		panic("no return value specified for Via")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func(notification.Notifiable) []string); ok {
		r0 = rf(notifiable)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// NotificationWithBackoff_Via_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Via'
type NotificationWithBackoff_Via_Call struct {
	*mock.Call
}

// Via is a helper method to define mock.On call
//   - notifiable notification.Notifiable
func (_e *NotificationWithBackoff_Expecter) Via(notifiable interface{}) *NotificationWithBackoff_Via_Call {
	return &NotificationWithBackoff_Via_Call{Call: _e.mock.On("Via", notifiable)}
}

func (_c *NotificationWithBackoff_Via_Call) Run(run func(notifiable notification.Notifiable)) *NotificationWithBackoff_Via_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(notification.Notifiable))
	})
	return _c
}

func (_c *NotificationWithBackoff_Via_Call) Return(_a0 []string) *NotificationWithBackoff_Via_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NotificationWithBackoff_Via_Call) RunAndReturn(run func(notification.Notifiable) []string) *NotificationWithBackoff_Via_Call {
	_c.Call.Return(run)
	return _c
}

// NewNotificationWithBackoff creates a new instance of NotificationWithBackoff. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationWithBackoff(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationWithBackoff {
	mock := &NotificationWithBackoff{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
