// Code generated by mockery. DO NOT EDIT.

package notification

import mock "github.com/stretchr/testify/mock"

// Notifiable is an autogenerated mock type for the Notifiable type
type Notifiable struct {
	mock.Mock
}

type Notifiable_Expecter struct {
	mock *mock.Mock
}

func (_m *Notifiable) EXPECT() *Notifiable_Expecter {
	return &Notifiable_Expecter{mock: &_m.Mock}
}

// NotificationParams provides a mock function with no fields
func (_m *Notifiable) NotificationParams() map[string]interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for NotificationParams")
	}

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// Notifiable_NotificationParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotificationParams'
type Notifiable_NotificationParams_Call struct {
	*mock.Call
}

// NotificationParams is a helper method to define mock.On call
func (_e *Notifiable_Expecter) NotificationParams() *Notifiable_NotificationParams_Call {
	return &Notifiable_NotificationParams_Call{Call: _e.mock.On("NotificationParams")}
}

func (_c *Notifiable_NotificationParams_Call) Run(run func()) *Notifiable_NotificationParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Notifiable_NotificationParams_Call) Return(_a0 map[string]interface{}) *Notifiable_NotificationParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Notifiable_NotificationParams_Call) RunAndReturn(run func() map[string]interface{}) *Notifiable_NotificationParams_Call {
	_c.Call.Return(run)
	return _c
}

// NewNotifiable creates a new instance of Notifiable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotifiable(t interface {
	mock.TestingT
	Cleanup(func())
}) *Notifiable {
	mock := &Notifiable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
