// Code generated by mockery. DO NOT EDIT.

package notification

import (
	notification "github.com/goravel/framework/contracts/notification"
	mock "github.com/stretchr/testify/mock"
)

// PayloadProvider is an autogenerated mock type for the PayloadProvider type
type PayloadProvider struct {
	mock.Mock
}

type PayloadProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *PayloadProvider) EXPECT() *PayloadProvider_Expecter {
	return &PayloadProvider_Expecter{mock: &_m.Mock}
}

// PayloadFor provides a mock function with given fields: channel, notifiable
func (_m *PayloadProvider) PayloadFor(channel string, notifiable notification.Notifiable) (map[string]interface{}, error) {
	ret := _m.Called(channel, notifiable)

	if len(ret) == 0 {
		panic("no return value specified for PayloadFor")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(string, notification.Notifiable) (map[string]interface{}, error)); ok {
		return rf(channel, notifiable)
	}
	if rf, ok := ret.Get(0).(func(string, notification.Notifiable) map[string]interface{}); ok {
		r0 = rf(channel, notifiable)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(string, notification.Notifiable) error); ok {
		r1 = rf(channel, notifiable)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PayloadProvider_PayloadFor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayloadFor'
type PayloadProvider_PayloadFor_Call struct {
	*mock.Call
}

// PayloadFor is a helper method to define mock.On call
//   - channel string
//   - notifiable notification.Notifiable
func (_e *PayloadProvider_Expecter) PayloadFor(channel interface{}, notifiable interface{}) *PayloadProvider_PayloadFor_Call {
	return &PayloadProvider_PayloadFor_Call{Call: _e.mock.On("PayloadFor", channel, notifiable)}
}

func (_c *PayloadProvider_PayloadFor_Call) Run(run func(channel string, notifiable notification.Notifiable)) *PayloadProvider_PayloadFor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(notification.Notifiable))
	})
	return _c
}

func (_c *PayloadProvider_PayloadFor_Call) Return(_a0 map[string]interface{}, _a1 error) *PayloadProvider_PayloadFor_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PayloadProvider_PayloadFor_Call) RunAndReturn(run func(string, notification.Notifiable) (map[string]interface{}, error)) *PayloadProvider_PayloadFor_Call {
	_c.Call.Return(run)
	return _c
}

// NewPayloadProvider creates a new instance of PayloadProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPayloadProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *PayloadProvider {
	mock := &PayloadProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
