// Code generated by mockery. DO NOT EDIT.

package ai

import (
	ai "github.com/goravel/framework/contracts/ai"
	mock "github.com/stretchr/testify/mock"
)

// AI is an autogenerated mock type for the AI type
type AI struct {
	mock.Mock
}

type AI_Expecter struct {
	mock *mock.Mock
}

func (_m *AI) EXPECT() *AI_Expecter {
	return &AI_Expecter{mock: &_m.Mock}
}

// Agent provides a mock function with given fields: agent, options
func (_m *AI) Agent(agent ai.Agent, options ...ai.Option) (ai.Conversation, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, agent)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Agent")
	}

	var r0 ai.Conversation
	var r1 error
	if rf, ok := ret.Get(0).(func(ai.Agent, ...ai.Option) (ai.Conversation, error)); ok {
		return rf(agent, options...)
	}
	if rf, ok := ret.Get(0).(func(ai.Agent, ...ai.Option) ai.Conversation); ok {
		r0 = rf(agent, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ai.Conversation)
		}
	}

	if rf, ok := ret.Get(1).(func(ai.Agent, ...ai.Option) error); ok {
		r1 = rf(agent, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AI_Agent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Agent'
type AI_Agent_Call struct {
	*mock.Call
}

// Agent is a helper method to define mock.On call
//   - agent ai.Agent
//   - options ...ai.Option
func (_e *AI_Expecter) Agent(agent interface{}, options ...interface{}) *AI_Agent_Call {
	return &AI_Agent_Call{Call: _e.mock.On("Agent",
		append([]interface{}{agent}, options...)...)}
}

func (_c *AI_Agent_Call) Run(run func(agent ai.Agent, options ...ai.Option)) *AI_Agent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]ai.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(ai.Option)
			}
		}
		run(args[0].(ai.Agent), variadicArgs...)
	})
	return _c
}

func (_c *AI_Agent_Call) Return(_a0 ai.Conversation, _a1 error) *AI_Agent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AI_Agent_Call) RunAndReturn(run func(ai.Agent, ...ai.Option) (ai.Conversation, error)) *AI_Agent_Call {
	_c.Call.Return(run)
	return _c
}

// NewAI creates a new instance of AI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAI(t interface {
	mock.TestingT
	Cleanup(func())
}) *AI {
	mock := &AI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
