// Code generated by mockery. DO NOT EDIT.

package ai

import (
	ai "github.com/goravel/framework/contracts/ai"
	mock "github.com/stretchr/testify/mock"
)

// Conversation is an autogenerated mock type for the Conversation type
type Conversation struct {
	mock.Mock
}

type Conversation_Expecter struct {
	mock *mock.Mock
}

func (_m *Conversation) EXPECT() *Conversation_Expecter {
	return &Conversation_Expecter{mock: &_m.Mock}
}

// Messages provides a mock function with no fields
func (_m *Conversation) Messages() []ai.Message {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Messages")
	}

	var r0 []ai.Message
	if rf, ok := ret.Get(0).(func() []ai.Message); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ai.Message)
		}
	}

	return r0
}

// Conversation_Messages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Messages'
type Conversation_Messages_Call struct {
	*mock.Call
}

// Messages is a helper method to define mock.On call
func (_e *Conversation_Expecter) Messages() *Conversation_Messages_Call {
	return &Conversation_Messages_Call{Call: _e.mock.On("Messages")}
}

func (_c *Conversation_Messages_Call) Run(run func()) *Conversation_Messages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Conversation_Messages_Call) Return(_a0 []ai.Message) *Conversation_Messages_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Conversation_Messages_Call) RunAndReturn(run func() []ai.Message) *Conversation_Messages_Call {
	_c.Call.Return(run)
	return _c
}

// Prompt provides a mock function with given fields: input
func (_m *Conversation) Prompt(input string) (ai.Response, error) {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Prompt")
	}

	var r0 ai.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (ai.Response, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(string) ai.Response); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ai.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Conversation_Prompt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prompt'
type Conversation_Prompt_Call struct {
	*mock.Call
}

// Prompt is a helper method to define mock.On call
//   - input string
func (_e *Conversation_Expecter) Prompt(input interface{}) *Conversation_Prompt_Call {
	return &Conversation_Prompt_Call{Call: _e.mock.On("Prompt", input)}
}

func (_c *Conversation_Prompt_Call) Run(run func(input string)) *Conversation_Prompt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Conversation_Prompt_Call) Return(_a0 ai.Response, _a1 error) *Conversation_Prompt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Conversation_Prompt_Call) RunAndReturn(run func(string) (ai.Response, error)) *Conversation_Prompt_Call {
	_c.Call.Return(run)
	return _c
}

// Reset provides a mock function with no fields
func (_m *Conversation) Reset() {
	_m.Called()
}

// Conversation_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type Conversation_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
func (_e *Conversation_Expecter) Reset() *Conversation_Reset_Call {
	return &Conversation_Reset_Call{Call: _e.mock.On("Reset")}
}

func (_c *Conversation_Reset_Call) Run(run func()) *Conversation_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Conversation_Reset_Call) Return() *Conversation_Reset_Call {
	_c.Call.Return()
	return _c
}

func (_c *Conversation_Reset_Call) RunAndReturn(run func()) *Conversation_Reset_Call {
	_c.Run(run)
	return _c
}

// NewConversation creates a new instance of Conversation. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConversation(t interface {
	mock.TestingT
	Cleanup(func())
}) *Conversation {
	mock := &Conversation{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
