// Code generated by mockery. DO NOT EDIT.

package ai

import (
	ai "github.com/goravel/framework/contracts/ai"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// ImageRequest is an autogenerated mock type for the ImageRequest type
type ImageRequest struct {
	mock.Mock
}

type ImageRequest_Expecter struct {
	mock *mock.Mock
}

func (_m *ImageRequest) EXPECT() *ImageRequest_Expecter {
	return &ImageRequest_Expecter{mock: &_m.Mock}
}

// Attachments provides a mock function with given fields: attachments
func (_m *ImageRequest) Attachments(attachments ...ai.Attachment) ai.ImageRequest {
	_va := make([]interface{}, len(attachments))
	for _i := range attachments {
		_va[_i] = attachments[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Attachments")
	}

	var r0 ai.ImageRequest
	if rf, ok := ret.Get(0).(func(...ai.Attachment) ai.ImageRequest); ok {
		r0 = rf(attachments...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ai.ImageRequest)
		}
	}

	return r0
}

// ImageRequest_Attachments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Attachments'
type ImageRequest_Attachments_Call struct {
	*mock.Call
}

// Attachments is a helper method to define mock.On call
//   - attachments ...ai.Attachment
func (_e *ImageRequest_Expecter) Attachments(attachments ...interface{}) *ImageRequest_Attachments_Call {
	return &ImageRequest_Attachments_Call{Call: _e.mock.On("Attachments",
		append([]interface{}{}, attachments...)...)}
}

func (_c *ImageRequest_Attachments_Call) Run(run func(attachments ...ai.Attachment)) *ImageRequest_Attachments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]ai.Attachment, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(ai.Attachment)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *ImageRequest_Attachments_Call) Return(_a0 ai.ImageRequest) *ImageRequest_Attachments_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ImageRequest_Attachments_Call) RunAndReturn(run func(...ai.Attachment) ai.ImageRequest) *ImageRequest_Attachments_Call {
	_c.Call.Return(run)
	return _c
}

// Generate provides a mock function with no fields
func (_m *ImageRequest) Generate() (ai.ImageResponse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 ai.ImageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() (ai.ImageResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() ai.ImageResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ai.ImageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ImageRequest_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type ImageRequest_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
func (_e *ImageRequest_Expecter) Generate() *ImageRequest_Generate_Call {
	return &ImageRequest_Generate_Call{Call: _e.mock.On("Generate")}
}

func (_c *ImageRequest_Generate_Call) Run(run func()) *ImageRequest_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ImageRequest_Generate_Call) Return(_a0 ai.ImageResponse, _a1 error) *ImageRequest_Generate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ImageRequest_Generate_Call) RunAndReturn(run func() (ai.ImageResponse, error)) *ImageRequest_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// Landscape provides a mock function with no fields
func (_m *ImageRequest) Landscape() ai.ImageRequest {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Landscape")
	}

	var r0 ai.ImageRequest
	if rf, ok := ret.Get(0).(func() ai.ImageRequest); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ai.ImageRequest)
		}
	}

	return r0
}

// ImageRequest_Landscape_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Landscape'
type ImageRequest_Landscape_Call struct {
	*mock.Call
}

// Landscape is a helper method to define mock.On call
func (_e *ImageRequest_Expecter) Landscape() *ImageRequest_Landscape_Call {
	return &ImageRequest_Landscape_Call{Call: _e.mock.On("Landscape")}
}

func (_c *ImageRequest_Landscape_Call) Run(run func()) *ImageRequest_Landscape_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ImageRequest_Landscape_Call) Return(_a0 ai.ImageRequest) *ImageRequest_Landscape_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ImageRequest_Landscape_Call) RunAndReturn(run func() ai.ImageRequest) *ImageRequest_Landscape_Call {
	_c.Call.Return(run)
	return _c
}

// Model provides a mock function with given fields: model
func (_m *ImageRequest) Model(model string) ai.ImageRequest {
	ret := _m.Called(model)

	if len(ret) == 0 {
		panic("no return value specified for Model")
	}

	var r0 ai.ImageRequest
	if rf, ok := ret.Get(0).(func(string) ai.ImageRequest); ok {
		r0 = rf(model)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ai.ImageRequest)
		}
	}

	return r0
}

// ImageRequest_Model_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Model'
type ImageRequest_Model_Call struct {
	*mock.Call
}

// Model is a helper method to define mock.On call
//   - model string
func (_e *ImageRequest_Expecter) Model(model interface{}) *ImageRequest_Model_Call {
	return &ImageRequest_Model_Call{Call: _e.mock.On("Model", model)}
}

func (_c *ImageRequest_Model_Call) Run(run func(model string)) *ImageRequest_Model_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ImageRequest_Model_Call) Return(_a0 ai.ImageRequest) *ImageRequest_Model_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ImageRequest_Model_Call) RunAndReturn(run func(string) ai.ImageRequest) *ImageRequest_Model_Call {
	_c.Call.Return(run)
	return _c
}

// Portrait provides a mock function with no fields
func (_m *ImageRequest) Portrait() ai.ImageRequest {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Portrait")
	}

	var r0 ai.ImageRequest
	if rf, ok := ret.Get(0).(func() ai.ImageRequest); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ai.ImageRequest)
		}
	}

	return r0
}

// ImageRequest_Portrait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Portrait'
type ImageRequest_Portrait_Call struct {
	*mock.Call
}

// Portrait is a helper method to define mock.On call
func (_e *ImageRequest_Expecter) Portrait() *ImageRequest_Portrait_Call {
	return &ImageRequest_Portrait_Call{Call: _e.mock.On("Portrait")}
}

func (_c *ImageRequest_Portrait_Call) Run(run func()) *ImageRequest_Portrait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ImageRequest_Portrait_Call) Return(_a0 ai.ImageRequest) *ImageRequest_Portrait_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ImageRequest_Portrait_Call) RunAndReturn(run func() ai.ImageRequest) *ImageRequest_Portrait_Call {
	_c.Call.Return(run)
	return _c
}

// Provider provides a mock function with given fields: provider, failovers
func (_m *ImageRequest) Provider(provider string, failovers ...string) ai.ImageRequest {
	_va := make([]interface{}, len(failovers))
	for _i := range failovers {
		_va[_i] = failovers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, provider)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Provider")
	}

	var r0 ai.ImageRequest
	if rf, ok := ret.Get(0).(func(string, ...string) ai.ImageRequest); ok {
		r0 = rf(provider, failovers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ai.ImageRequest)
		}
	}

	return r0
}

// ImageRequest_Provider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Provider'
type ImageRequest_Provider_Call struct {
	*mock.Call
}

// Provider is a helper method to define mock.On call
//   - provider string
//   - failovers ...string
func (_e *ImageRequest_Expecter) Provider(provider interface{}, failovers ...interface{}) *ImageRequest_Provider_Call {
	return &ImageRequest_Provider_Call{Call: _e.mock.On("Provider",
		append([]interface{}{provider}, failovers...)...)}
}

func (_c *ImageRequest_Provider_Call) Run(run func(provider string, failovers ...string)) *ImageRequest_Provider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *ImageRequest_Provider_Call) Return(_a0 ai.ImageRequest) *ImageRequest_Provider_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ImageRequest_Provider_Call) RunAndReturn(run func(string, ...string) ai.ImageRequest) *ImageRequest_Provider_Call {
	_c.Call.Return(run)
	return _c
}

// Quality provides a mock function with given fields: quality
func (_m *ImageRequest) Quality(quality ai.ImageQuality) ai.ImageRequest {
	ret := _m.Called(quality)

	if len(ret) == 0 {
		panic("no return value specified for Quality")
	}

	var r0 ai.ImageRequest
	if rf, ok := ret.Get(0).(func(ai.ImageQuality) ai.ImageRequest); ok {
		r0 = rf(quality)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ai.ImageRequest)
		}
	}

	return r0
}

// ImageRequest_Quality_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Quality'
type ImageRequest_Quality_Call struct {
	*mock.Call
}

// Quality is a helper method to define mock.On call
//   - quality ai.ImageQuality
func (_e *ImageRequest_Expecter) Quality(quality interface{}) *ImageRequest_Quality_Call {
	return &ImageRequest_Quality_Call{Call: _e.mock.On("Quality", quality)}
}

func (_c *ImageRequest_Quality_Call) Run(run func(quality ai.ImageQuality)) *ImageRequest_Quality_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ai.ImageQuality))
	})
	return _c
}

func (_c *ImageRequest_Quality_Call) Return(_a0 ai.ImageRequest) *ImageRequest_Quality_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ImageRequest_Quality_Call) RunAndReturn(run func(ai.ImageQuality) ai.ImageRequest) *ImageRequest_Quality_Call {
	_c.Call.Return(run)
	return _c
}

// Square provides a mock function with no fields
func (_m *ImageRequest) Square() ai.ImageRequest {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Square")
	}

	var r0 ai.ImageRequest
	if rf, ok := ret.Get(0).(func() ai.ImageRequest); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ai.ImageRequest)
		}
	}

	return r0
}

// ImageRequest_Square_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Square'
type ImageRequest_Square_Call struct {
	*mock.Call
}

// Square is a helper method to define mock.On call
func (_e *ImageRequest_Expecter) Square() *ImageRequest_Square_Call {
	return &ImageRequest_Square_Call{Call: _e.mock.On("Square")}
}

func (_c *ImageRequest_Square_Call) Run(run func()) *ImageRequest_Square_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ImageRequest_Square_Call) Return(_a0 ai.ImageRequest) *ImageRequest_Square_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ImageRequest_Square_Call) RunAndReturn(run func() ai.ImageRequest) *ImageRequest_Square_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function with given fields: disk
func (_m *ImageRequest) Store(disk ...string) (string, error) {
	_va := make([]interface{}, len(disk))
	for _i := range disk {
		_va[_i] = disk[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(...string) (string, error)); ok {
		return rf(disk...)
	}
	if rf, ok := ret.Get(0).(func(...string) string); ok {
		r0 = rf(disk...)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(...string) error); ok {
		r1 = rf(disk...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ImageRequest_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type ImageRequest_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - disk ...string
func (_e *ImageRequest_Expecter) Store(disk ...interface{}) *ImageRequest_Store_Call {
	return &ImageRequest_Store_Call{Call: _e.mock.On("Store",
		append([]interface{}{}, disk...)...)}
}

func (_c *ImageRequest_Store_Call) Run(run func(disk ...string)) *ImageRequest_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *ImageRequest_Store_Call) Return(_a0 string, _a1 error) *ImageRequest_Store_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ImageRequest_Store_Call) RunAndReturn(run func(...string) (string, error)) *ImageRequest_Store_Call {
	_c.Call.Return(run)
	return _c
}

// StoreAs provides a mock function with given fields: path, disk
func (_m *ImageRequest) StoreAs(path string, disk ...string) (string, error) {
	_va := make([]interface{}, len(disk))
	for _i := range disk {
		_va[_i] = disk[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, path)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for StoreAs")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, ...string) (string, error)); ok {
		return rf(path, disk...)
	}
	if rf, ok := ret.Get(0).(func(string, ...string) string); ok {
		r0 = rf(path, disk...)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, ...string) error); ok {
		r1 = rf(path, disk...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ImageRequest_StoreAs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreAs'
type ImageRequest_StoreAs_Call struct {
	*mock.Call
}

// StoreAs is a helper method to define mock.On call
//   - path string
//   - disk ...string
func (_e *ImageRequest_Expecter) StoreAs(path interface{}, disk ...interface{}) *ImageRequest_StoreAs_Call {
	return &ImageRequest_StoreAs_Call{Call: _e.mock.On("StoreAs",
		append([]interface{}{path}, disk...)...)}
}

func (_c *ImageRequest_StoreAs_Call) Run(run func(path string, disk ...string)) *ImageRequest_StoreAs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *ImageRequest_StoreAs_Call) Return(_a0 string, _a1 error) *ImageRequest_StoreAs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ImageRequest_StoreAs_Call) RunAndReturn(run func(string, ...string) (string, error)) *ImageRequest_StoreAs_Call {
	_c.Call.Return(run)
	return _c
}

// Timeout provides a mock function with given fields: timeout
func (_m *ImageRequest) Timeout(timeout time.Duration) ai.ImageRequest {
	ret := _m.Called(timeout)

	if len(ret) == 0 {
		panic("no return value specified for Timeout")
	}

	var r0 ai.ImageRequest
	if rf, ok := ret.Get(0).(func(time.Duration) ai.ImageRequest); ok {
		r0 = rf(timeout)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ai.ImageRequest)
		}
	}

	return r0
}

// ImageRequest_Timeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Timeout'
type ImageRequest_Timeout_Call struct {
	*mock.Call
}

// Timeout is a helper method to define mock.On call
//   - timeout time.Duration
func (_e *ImageRequest_Expecter) Timeout(timeout interface{}) *ImageRequest_Timeout_Call {
	return &ImageRequest_Timeout_Call{Call: _e.mock.On("Timeout", timeout)}
}

func (_c *ImageRequest_Timeout_Call) Run(run func(timeout time.Duration)) *ImageRequest_Timeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Duration))
	})
	return _c
}

func (_c *ImageRequest_Timeout_Call) Return(_a0 ai.ImageRequest) *ImageRequest_Timeout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ImageRequest_Timeout_Call) RunAndReturn(run func(time.Duration) ai.ImageRequest) *ImageRequest_Timeout_Call {
	_c.Call.Return(run)
	return _c
}

// NewImageRequest creates a new instance of ImageRequest. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewImageRequest(t interface {
	mock.TestingT
	Cleanup(func())
}) *ImageRequest {
	mock := &ImageRequest{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
