// Code generated by mockery. DO NOT EDIT.

package ai

import (
	ai "github.com/goravel/framework/contracts/ai"
	mock "github.com/stretchr/testify/mock"
)

// PromptOption is an autogenerated mock type for the PromptOption type
type PromptOption struct {
	mock.Mock
}

type PromptOption_Expecter struct {
	mock *mock.Mock
}

func (_m *PromptOption) EXPECT() *PromptOption_Expecter {
	return &PromptOption_Expecter{mock: &_m.Mock}
}

// ApplyPrompt provides a mock function with given fields: options
func (_m *PromptOption) ApplyPrompt(options *ai.PromptOptions) {
	_m.Called(options)
}

// PromptOption_ApplyPrompt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyPrompt'
type PromptOption_ApplyPrompt_Call struct {
	*mock.Call
}

// ApplyPrompt is a helper method to define mock.On call
//   - options *ai.PromptOptions
func (_e *PromptOption_Expecter) ApplyPrompt(options interface{}) *PromptOption_ApplyPrompt_Call {
	return &PromptOption_ApplyPrompt_Call{Call: _e.mock.On("ApplyPrompt", options)}
}

func (_c *PromptOption_ApplyPrompt_Call) Run(run func(options *ai.PromptOptions)) *PromptOption_ApplyPrompt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*ai.PromptOptions))
	})
	return _c
}

func (_c *PromptOption_ApplyPrompt_Call) Return() *PromptOption_ApplyPrompt_Call {
	_c.Call.Return()
	return _c
}

func (_c *PromptOption_ApplyPrompt_Call) RunAndReturn(run func(*ai.PromptOptions)) *PromptOption_ApplyPrompt_Call {
	_c.Run(run)
	return _c
}

// NewPromptOption creates a new instance of PromptOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPromptOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *PromptOption {
	mock := &PromptOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
