// Code generated by mockery. DO NOT EDIT.

package ai

import (
	context "context"

	ai "github.com/goravel/framework/contracts/ai"

	mock "github.com/stretchr/testify/mock"
)

// Provider is an autogenerated mock type for the Provider type
type Provider struct {
	mock.Mock
}

type Provider_Expecter struct {
	mock *mock.Mock
}

func (_m *Provider) EXPECT() *Provider_Expecter {
	return &Provider_Expecter{mock: &_m.Mock}
}

// Prompt provides a mock function with given fields: ctx, prompt
func (_m *Provider) Prompt(ctx context.Context, prompt ai.AgentPrompt) (ai.Response, error) {
	ret := _m.Called(ctx, prompt)

	if len(ret) == 0 {
		panic("no return value specified for Prompt")
	}

	var r0 ai.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ai.AgentPrompt) (ai.Response, error)); ok {
		return rf(ctx, prompt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ai.AgentPrompt) ai.Response); ok {
		r0 = rf(ctx, prompt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ai.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ai.AgentPrompt) error); ok {
		r1 = rf(ctx, prompt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Provider_Prompt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prompt'
type Provider_Prompt_Call struct {
	*mock.Call
}

// Prompt is a helper method to define mock.On call
//   - ctx context.Context
//   - prompt ai.AgentPrompt
func (_e *Provider_Expecter) Prompt(ctx interface{}, prompt interface{}) *Provider_Prompt_Call {
	return &Provider_Prompt_Call{Call: _e.mock.On("Prompt", ctx, prompt)}
}

func (_c *Provider_Prompt_Call) Run(run func(ctx context.Context, prompt ai.AgentPrompt)) *Provider_Prompt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ai.AgentPrompt))
	})
	return _c
}

func (_c *Provider_Prompt_Call) Return(_a0 ai.Response, _a1 error) *Provider_Prompt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Provider_Prompt_Call) RunAndReturn(run func(context.Context, ai.AgentPrompt) (ai.Response, error)) *Provider_Prompt_Call {
	_c.Call.Return(run)
	return _c
}

// NewProvider creates a new instance of Provider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *Provider {
	mock := &Provider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
