// Code generated by mockery. DO NOT EDIT.

package ai

import (
	ai "github.com/goravel/framework/contracts/ai"
	http "github.com/goravel/framework/contracts/http"

	mock "github.com/stretchr/testify/mock"
)

// RenderFunc is an autogenerated mock type for the RenderFunc type
type RenderFunc struct {
	mock.Mock
}

type RenderFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *RenderFunc) EXPECT() *RenderFunc_Expecter {
	return &RenderFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: w, event
func (_m *RenderFunc) Execute(w http.StreamWriter, event ai.StreamEvent) error {
	ret := _m.Called(w, event)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(http.StreamWriter, ai.StreamEvent) error); ok {
		r0 = rf(w, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RenderFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type RenderFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - w http.StreamWriter
//   - event ai.StreamEvent
func (_e *RenderFunc_Expecter) Execute(w interface{}, event interface{}) *RenderFunc_Execute_Call {
	return &RenderFunc_Execute_Call{Call: _e.mock.On("Execute", w, event)}
}

func (_c *RenderFunc_Execute_Call) Run(run func(w http.StreamWriter, event ai.StreamEvent)) *RenderFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.StreamWriter), args[1].(ai.StreamEvent))
	})
	return _c
}

func (_c *RenderFunc_Execute_Call) Return(_a0 error) *RenderFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RenderFunc_Execute_Call) RunAndReturn(run func(http.StreamWriter, ai.StreamEvent) error) *RenderFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewRenderFunc creates a new instance of RenderFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRenderFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *RenderFunc {
	mock := &RenderFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
