// Code generated by mockery. DO NOT EDIT.

package ai

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Tool is an autogenerated mock type for the Tool type
type Tool struct {
	mock.Mock
}

type Tool_Expecter struct {
	mock *mock.Mock
}

func (_m *Tool) EXPECT() *Tool_Expecter {
	return &Tool_Expecter{mock: &_m.Mock}
}

// Description provides a mock function with no fields
func (_m *Tool) Description() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Description")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Tool_Description_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Description'
type Tool_Description_Call struct {
	*mock.Call
}

// Description is a helper method to define mock.On call
func (_e *Tool_Expecter) Description() *Tool_Description_Call {
	return &Tool_Description_Call{Call: _e.mock.On("Description")}
}

func (_c *Tool_Description_Call) Run(run func()) *Tool_Description_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Tool_Description_Call) Return(_a0 string) *Tool_Description_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Tool_Description_Call) RunAndReturn(run func() string) *Tool_Description_Call {
	_c.Call.Return(run)
	return _c
}

// Execute provides a mock function with given fields: ctx, args
func (_m *Tool) Execute(ctx context.Context, args map[string]interface{}) (string, error) {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}) (string, error)); ok {
		return rf(ctx, args)
	}
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}) string); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, map[string]interface{}) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Tool_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type Tool_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - args map[string]interface{}
func (_e *Tool_Expecter) Execute(ctx interface{}, args interface{}) *Tool_Execute_Call {
	return &Tool_Execute_Call{Call: _e.mock.On("Execute", ctx, args)}
}

func (_c *Tool_Execute_Call) Run(run func(ctx context.Context, args map[string]interface{})) *Tool_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(map[string]interface{}))
	})
	return _c
}

func (_c *Tool_Execute_Call) Return(_a0 string, _a1 error) *Tool_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Tool_Execute_Call) RunAndReturn(run func(context.Context, map[string]interface{}) (string, error)) *Tool_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *Tool) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Tool_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type Tool_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *Tool_Expecter) Name() *Tool_Name_Call {
	return &Tool_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *Tool_Name_Call) Run(run func()) *Tool_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Tool_Name_Call) Return(_a0 string) *Tool_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Tool_Name_Call) RunAndReturn(run func() string) *Tool_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Parameters provides a mock function with no fields
func (_m *Tool) Parameters() map[string]interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Parameters")
	}

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// Tool_Parameters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parameters'
type Tool_Parameters_Call struct {
	*mock.Call
}

// Parameters is a helper method to define mock.On call
func (_e *Tool_Expecter) Parameters() *Tool_Parameters_Call {
	return &Tool_Parameters_Call{Call: _e.mock.On("Parameters")}
}

func (_c *Tool_Parameters_Call) Run(run func()) *Tool_Parameters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Tool_Parameters_Call) Return(_a0 map[string]interface{}) *Tool_Parameters_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Tool_Parameters_Call) RunAndReturn(run func() map[string]interface{}) *Tool_Parameters_Call {
	_c.Call.Return(run)
	return _c
}

// NewTool creates a new instance of Tool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTool(t interface {
	mock.TestingT
	Cleanup(func())
}) *Tool {
	mock := &Tool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
