package contracts

const (
	BindingArtisan     = "goravel.artisan"
	BindingAuth        = "goravel.auth"
	BindingCache       = "goravel.cache"
	BindingConfig      = "goravel.config"
	BindingCrypt       = "goravel.crypt"
	BindingDB          = "goravel.db"
	BindingEvent       = "goravel.event"
	BindingGate        = "goravel.gate"
	BindingGrpc        = "goravel.grpc"
	BindingHash        = "goravel.hash"
	BindingHttp        = "goravel.http"
	BindingLang        = "goravel.lang"
	BindingLog         = "goravel.log"
	BindingMail        = "goravel.mail"
	BindingOrm         = "goravel.orm"
	BindingQueue       = "goravel.queue"
	BindingRateLimiter = "goravel.rate_limiter"
	BindingRoute       = "goravel.route"
	BindingSchedule    = "goravel.schedule"
	BindingSchema      = "goravel.schema"
	BindingSeeder      = "goravel.seeder"
	BindingSession     = "goravel.session"
	BindingStorage     = "goravel.storage"
	BindingTesting     = "goravel.testing"
	BindingValidation  = "goravel.validation"
	BindingView        = "goravel.view"
)
