// Code generated by mockery. DO NOT EDIT.

package log

import (
	log "github.com/goravel/framework/contracts/log"
	mock "github.com/stretchr/testify/mock"
)

// Handler is an autogenerated mock type for the Handler type
type Handler struct {
	mock.Mock
}

type Handler_Expecter struct {
	mock *mock.Mock
}

func (_m *Handler) EXPECT() *Handler_Expecter {
	return &Handler_Expecter{mock: &_m.Mock}
}

// Enabled provides a mock function with given fields: _a0
func (_m *Handler) Enabled(_a0 log.Level) bool {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Enabled")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(log.Level) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Handler_Enabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enabled'
type Handler_Enabled_Call struct {
	*mock.Call
}

// Enabled is a helper method to define mock.On call
//   - _a0 log.Level
func (_e *Handler_Expecter) Enabled(_a0 interface{}) *Handler_Enabled_Call {
	return &Handler_Enabled_Call{Call: _e.mock.On("Enabled", _a0)}
}

func (_c *Handler_Enabled_Call) Run(run func(_a0 log.Level)) *Handler_Enabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(log.Level))
	})
	return _c
}

func (_c *Handler_Enabled_Call) Return(_a0 bool) *Handler_Enabled_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Handler_Enabled_Call) RunAndReturn(run func(log.Level) bool) *Handler_Enabled_Call {
	_c.Call.Return(run)
	return _c
}

// Handle provides a mock function with given fields: _a0
func (_m *Handler) Handle(_a0 log.Entry) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(log.Entry) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Handler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type Handler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - _a0 log.Entry
func (_e *Handler_Expecter) Handle(_a0 interface{}) *Handler_Handle_Call {
	return &Handler_Handle_Call{Call: _e.mock.On("Handle", _a0)}
}

func (_c *Handler_Handle_Call) Run(run func(_a0 log.Entry)) *Handler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(log.Entry))
	})
	return _c
}

func (_c *Handler_Handle_Call) Return(_a0 error) *Handler_Handle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Handler_Handle_Call) RunAndReturn(run func(log.Entry) error) *Handler_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewHandler creates a new instance of Handler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *Handler {
	mock := &Handler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
