// Code generated by mockery. DO NOT EDIT.

package log

import (
	http "github.com/goravel/framework/contracts/http"
	log "github.com/goravel/framework/contracts/log"
	mock "github.com/stretchr/testify/mock"
)

// Writer is an autogenerated mock type for the Writer type
type Writer struct {
	mock.Mock
}

type Writer_Expecter struct {
	mock *mock.Mock
}

func (_m *Writer) EXPECT() *Writer_Expecter {
	return &Writer_Expecter{mock: &_m.Mock}
}

// Code provides a mock function with given fields: code
func (_m *Writer) Code(code string) log.Writer {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for Code")
	}

	var r0 log.Writer
	if rf, ok := ret.Get(0).(func(string) log.Writer); ok {
		r0 = rf(code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(log.Writer)
		}
	}

	return r0
}

// Writer_Code_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Code'
type Writer_Code_Call struct {
	*mock.Call
}

// Code is a helper method to define mock.On call
//   - code string
func (_e *Writer_Expecter) Code(code interface{}) *Writer_Code_Call {
	return &Writer_Code_Call{Call: _e.mock.On("Code", code)}
}

func (_c *Writer_Code_Call) Run(run func(code string)) *Writer_Code_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Writer_Code_Call) Return(_a0 log.Writer) *Writer_Code_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Writer_Code_Call) RunAndReturn(run func(string) log.Writer) *Writer_Code_Call {
	_c.Call.Return(run)
	return _c
}

// Debug provides a mock function with given fields: args
func (_m *Writer) Debug(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Writer_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type Writer_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - args ...interface{}
func (_e *Writer_Expecter) Debug(args ...interface{}) *Writer_Debug_Call {
	return &Writer_Debug_Call{Call: _e.mock.On("Debug",
		append([]interface{}{}, args...)...)}
}

func (_c *Writer_Debug_Call) Run(run func(args ...interface{})) *Writer_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *Writer_Debug_Call) Return() *Writer_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *Writer_Debug_Call) RunAndReturn(run func(...interface{})) *Writer_Debug_Call {
	_c.Run(run)
	return _c
}

// Debugf provides a mock function with given fields: format, args
func (_m *Writer) Debugf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Writer_Debugf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debugf'
type Writer_Debugf_Call struct {
	*mock.Call
}

// Debugf is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *Writer_Expecter) Debugf(format interface{}, args ...interface{}) *Writer_Debugf_Call {
	return &Writer_Debugf_Call{Call: _e.mock.On("Debugf",
		append([]interface{}{format}, args...)...)}
}

func (_c *Writer_Debugf_Call) Run(run func(format string, args ...interface{})) *Writer_Debugf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *Writer_Debugf_Call) Return() *Writer_Debugf_Call {
	_c.Call.Return()
	return _c
}

func (_c *Writer_Debugf_Call) RunAndReturn(run func(string, ...interface{})) *Writer_Debugf_Call {
	_c.Run(run)
	return _c
}

// Error provides a mock function with given fields: args
func (_m *Writer) Error(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Writer_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type Writer_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - args ...interface{}
func (_e *Writer_Expecter) Error(args ...interface{}) *Writer_Error_Call {
	return &Writer_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{}, args...)...)}
}

func (_c *Writer_Error_Call) Run(run func(args ...interface{})) *Writer_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *Writer_Error_Call) Return() *Writer_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *Writer_Error_Call) RunAndReturn(run func(...interface{})) *Writer_Error_Call {
	_c.Run(run)
	return _c
}

// Errorf provides a mock function with given fields: format, args
func (_m *Writer) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Writer_Errorf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Errorf'
type Writer_Errorf_Call struct {
	*mock.Call
}

// Errorf is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *Writer_Expecter) Errorf(format interface{}, args ...interface{}) *Writer_Errorf_Call {
	return &Writer_Errorf_Call{Call: _e.mock.On("Errorf",
		append([]interface{}{format}, args...)...)}
}

func (_c *Writer_Errorf_Call) Run(run func(format string, args ...interface{})) *Writer_Errorf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *Writer_Errorf_Call) Return() *Writer_Errorf_Call {
	_c.Call.Return()
	return _c
}

func (_c *Writer_Errorf_Call) RunAndReturn(run func(string, ...interface{})) *Writer_Errorf_Call {
	_c.Run(run)
	return _c
}

// Fatal provides a mock function with given fields: args
func (_m *Writer) Fatal(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Writer_Fatal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fatal'
type Writer_Fatal_Call struct {
	*mock.Call
}

// Fatal is a helper method to define mock.On call
//   - args ...interface{}
func (_e *Writer_Expecter) Fatal(args ...interface{}) *Writer_Fatal_Call {
	return &Writer_Fatal_Call{Call: _e.mock.On("Fatal",
		append([]interface{}{}, args...)...)}
}

func (_c *Writer_Fatal_Call) Run(run func(args ...interface{})) *Writer_Fatal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *Writer_Fatal_Call) Return() *Writer_Fatal_Call {
	_c.Call.Return()
	return _c
}

func (_c *Writer_Fatal_Call) RunAndReturn(run func(...interface{})) *Writer_Fatal_Call {
	_c.Run(run)
	return _c
}

// Fatalf provides a mock function with given fields: format, args
func (_m *Writer) Fatalf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Writer_Fatalf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fatalf'
type Writer_Fatalf_Call struct {
	*mock.Call
}

// Fatalf is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *Writer_Expecter) Fatalf(format interface{}, args ...interface{}) *Writer_Fatalf_Call {
	return &Writer_Fatalf_Call{Call: _e.mock.On("Fatalf",
		append([]interface{}{format}, args...)...)}
}

func (_c *Writer_Fatalf_Call) Run(run func(format string, args ...interface{})) *Writer_Fatalf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *Writer_Fatalf_Call) Return() *Writer_Fatalf_Call {
	_c.Call.Return()
	return _c
}

func (_c *Writer_Fatalf_Call) RunAndReturn(run func(string, ...interface{})) *Writer_Fatalf_Call {
	_c.Run(run)
	return _c
}

// Hint provides a mock function with given fields: hint
func (_m *Writer) Hint(hint string) log.Writer {
	ret := _m.Called(hint)

	if len(ret) == 0 {
		panic("no return value specified for Hint")
	}

	var r0 log.Writer
	if rf, ok := ret.Get(0).(func(string) log.Writer); ok {
		r0 = rf(hint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(log.Writer)
		}
	}

	return r0
}

// Writer_Hint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hint'
type Writer_Hint_Call struct {
	*mock.Call
}

// Hint is a helper method to define mock.On call
//   - hint string
func (_e *Writer_Expecter) Hint(hint interface{}) *Writer_Hint_Call {
	return &Writer_Hint_Call{Call: _e.mock.On("Hint", hint)}
}

func (_c *Writer_Hint_Call) Run(run func(hint string)) *Writer_Hint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Writer_Hint_Call) Return(_a0 log.Writer) *Writer_Hint_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Writer_Hint_Call) RunAndReturn(run func(string) log.Writer) *Writer_Hint_Call {
	_c.Call.Return(run)
	return _c
}

// In provides a mock function with given fields: domain
func (_m *Writer) In(domain string) log.Writer {
	ret := _m.Called(domain)

	if len(ret) == 0 {
		panic("no return value specified for In")
	}

	var r0 log.Writer
	if rf, ok := ret.Get(0).(func(string) log.Writer); ok {
		r0 = rf(domain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(log.Writer)
		}
	}

	return r0
}

// Writer_In_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'In'
type Writer_In_Call struct {
	*mock.Call
}

// In is a helper method to define mock.On call
//   - domain string
func (_e *Writer_Expecter) In(domain interface{}) *Writer_In_Call {
	return &Writer_In_Call{Call: _e.mock.On("In", domain)}
}

func (_c *Writer_In_Call) Run(run func(domain string)) *Writer_In_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Writer_In_Call) Return(_a0 log.Writer) *Writer_In_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Writer_In_Call) RunAndReturn(run func(string) log.Writer) *Writer_In_Call {
	_c.Call.Return(run)
	return _c
}

// Info provides a mock function with given fields: args
func (_m *Writer) Info(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Writer_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type Writer_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - args ...interface{}
func (_e *Writer_Expecter) Info(args ...interface{}) *Writer_Info_Call {
	return &Writer_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{}, args...)...)}
}

func (_c *Writer_Info_Call) Run(run func(args ...interface{})) *Writer_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *Writer_Info_Call) Return() *Writer_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *Writer_Info_Call) RunAndReturn(run func(...interface{})) *Writer_Info_Call {
	_c.Run(run)
	return _c
}

// Infof provides a mock function with given fields: format, args
func (_m *Writer) Infof(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Writer_Infof_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Infof'
type Writer_Infof_Call struct {
	*mock.Call
}

// Infof is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *Writer_Expecter) Infof(format interface{}, args ...interface{}) *Writer_Infof_Call {
	return &Writer_Infof_Call{Call: _e.mock.On("Infof",
		append([]interface{}{format}, args...)...)}
}

func (_c *Writer_Infof_Call) Run(run func(format string, args ...interface{})) *Writer_Infof_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *Writer_Infof_Call) Return() *Writer_Infof_Call {
	_c.Call.Return()
	return _c
}

func (_c *Writer_Infof_Call) RunAndReturn(run func(string, ...interface{})) *Writer_Infof_Call {
	_c.Run(run)
	return _c
}

// Owner provides a mock function with given fields: owner
func (_m *Writer) Owner(owner interface{}) log.Writer {
	ret := _m.Called(owner)

	if len(ret) == 0 {
		panic("no return value specified for Owner")
	}

	var r0 log.Writer
	if rf, ok := ret.Get(0).(func(interface{}) log.Writer); ok {
		r0 = rf(owner)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(log.Writer)
		}
	}

	return r0
}

// Writer_Owner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Owner'
type Writer_Owner_Call struct {
	*mock.Call
}

// Owner is a helper method to define mock.On call
//   - owner interface{}
func (_e *Writer_Expecter) Owner(owner interface{}) *Writer_Owner_Call {
	return &Writer_Owner_Call{Call: _e.mock.On("Owner", owner)}
}

func (_c *Writer_Owner_Call) Run(run func(owner interface{})) *Writer_Owner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *Writer_Owner_Call) Return(_a0 log.Writer) *Writer_Owner_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Writer_Owner_Call) RunAndReturn(run func(interface{}) log.Writer) *Writer_Owner_Call {
	_c.Call.Return(run)
	return _c
}

// Panic provides a mock function with given fields: args
func (_m *Writer) Panic(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Writer_Panic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Panic'
type Writer_Panic_Call struct {
	*mock.Call
}

// Panic is a helper method to define mock.On call
//   - args ...interface{}
func (_e *Writer_Expecter) Panic(args ...interface{}) *Writer_Panic_Call {
	return &Writer_Panic_Call{Call: _e.mock.On("Panic",
		append([]interface{}{}, args...)...)}
}

func (_c *Writer_Panic_Call) Run(run func(args ...interface{})) *Writer_Panic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *Writer_Panic_Call) Return() *Writer_Panic_Call {
	_c.Call.Return()
	return _c
}

func (_c *Writer_Panic_Call) RunAndReturn(run func(...interface{})) *Writer_Panic_Call {
	_c.Run(run)
	return _c
}

// Panicf provides a mock function with given fields: format, args
func (_m *Writer) Panicf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Writer_Panicf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Panicf'
type Writer_Panicf_Call struct {
	*mock.Call
}

// Panicf is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *Writer_Expecter) Panicf(format interface{}, args ...interface{}) *Writer_Panicf_Call {
	return &Writer_Panicf_Call{Call: _e.mock.On("Panicf",
		append([]interface{}{format}, args...)...)}
}

func (_c *Writer_Panicf_Call) Run(run func(format string, args ...interface{})) *Writer_Panicf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *Writer_Panicf_Call) Return() *Writer_Panicf_Call {
	_c.Call.Return()
	return _c
}

func (_c *Writer_Panicf_Call) RunAndReturn(run func(string, ...interface{})) *Writer_Panicf_Call {
	_c.Run(run)
	return _c
}

// Request provides a mock function with given fields: req
func (_m *Writer) Request(req http.ContextRequest) log.Writer {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Request")
	}

	var r0 log.Writer
	if rf, ok := ret.Get(0).(func(http.ContextRequest) log.Writer); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(log.Writer)
		}
	}

	return r0
}

// Writer_Request_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Request'
type Writer_Request_Call struct {
	*mock.Call
}

// Request is a helper method to define mock.On call
//   - req http.ContextRequest
func (_e *Writer_Expecter) Request(req interface{}) *Writer_Request_Call {
	return &Writer_Request_Call{Call: _e.mock.On("Request", req)}
}

func (_c *Writer_Request_Call) Run(run func(req http.ContextRequest)) *Writer_Request_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ContextRequest))
	})
	return _c
}

func (_c *Writer_Request_Call) Return(_a0 log.Writer) *Writer_Request_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Writer_Request_Call) RunAndReturn(run func(http.ContextRequest) log.Writer) *Writer_Request_Call {
	_c.Call.Return(run)
	return _c
}

// Response provides a mock function with given fields: res
func (_m *Writer) Response(res http.ContextResponse) log.Writer {
	ret := _m.Called(res)

	if len(ret) == 0 {
		panic("no return value specified for Response")
	}

	var r0 log.Writer
	if rf, ok := ret.Get(0).(func(http.ContextResponse) log.Writer); ok {
		r0 = rf(res)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(log.Writer)
		}
	}

	return r0
}

// Writer_Response_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Response'
type Writer_Response_Call struct {
	*mock.Call
}

// Response is a helper method to define mock.On call
//   - res http.ContextResponse
func (_e *Writer_Expecter) Response(res interface{}) *Writer_Response_Call {
	return &Writer_Response_Call{Call: _e.mock.On("Response", res)}
}

func (_c *Writer_Response_Call) Run(run func(res http.ContextResponse)) *Writer_Response_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ContextResponse))
	})
	return _c
}

func (_c *Writer_Response_Call) Return(_a0 log.Writer) *Writer_Response_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Writer_Response_Call) RunAndReturn(run func(http.ContextResponse) log.Writer) *Writer_Response_Call {
	_c.Call.Return(run)
	return _c
}

// Tags provides a mock function with given fields: tags
func (_m *Writer) Tags(tags ...string) log.Writer {
	_va := make([]interface{}, len(tags))
	for _i := range tags {
		_va[_i] = tags[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Tags")
	}

	var r0 log.Writer
	if rf, ok := ret.Get(0).(func(...string) log.Writer); ok {
		r0 = rf(tags...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(log.Writer)
		}
	}

	return r0
}

// Writer_Tags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tags'
type Writer_Tags_Call struct {
	*mock.Call
}

// Tags is a helper method to define mock.On call
//   - tags ...string
func (_e *Writer_Expecter) Tags(tags ...interface{}) *Writer_Tags_Call {
	return &Writer_Tags_Call{Call: _e.mock.On("Tags",
		append([]interface{}{}, tags...)...)}
}

func (_c *Writer_Tags_Call) Run(run func(tags ...string)) *Writer_Tags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *Writer_Tags_Call) Return(_a0 log.Writer) *Writer_Tags_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Writer_Tags_Call) RunAndReturn(run func(...string) log.Writer) *Writer_Tags_Call {
	_c.Call.Return(run)
	return _c
}

// User provides a mock function with given fields: user
func (_m *Writer) User(user interface{}) log.Writer {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for User")
	}

	var r0 log.Writer
	if rf, ok := ret.Get(0).(func(interface{}) log.Writer); ok {
		r0 = rf(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(log.Writer)
		}
	}

	return r0
}

// Writer_User_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'User'
type Writer_User_Call struct {
	*mock.Call
}

// User is a helper method to define mock.On call
//   - user interface{}
func (_e *Writer_Expecter) User(user interface{}) *Writer_User_Call {
	return &Writer_User_Call{Call: _e.mock.On("User", user)}
}

func (_c *Writer_User_Call) Run(run func(user interface{})) *Writer_User_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *Writer_User_Call) Return(_a0 log.Writer) *Writer_User_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Writer_User_Call) RunAndReturn(run func(interface{}) log.Writer) *Writer_User_Call {
	_c.Call.Return(run)
	return _c
}

// Warning provides a mock function with given fields: args
func (_m *Writer) Warning(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Writer_Warning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warning'
type Writer_Warning_Call struct {
	*mock.Call
}

// Warning is a helper method to define mock.On call
//   - args ...interface{}
func (_e *Writer_Expecter) Warning(args ...interface{}) *Writer_Warning_Call {
	return &Writer_Warning_Call{Call: _e.mock.On("Warning",
		append([]interface{}{}, args...)...)}
}

func (_c *Writer_Warning_Call) Run(run func(args ...interface{})) *Writer_Warning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *Writer_Warning_Call) Return() *Writer_Warning_Call {
	_c.Call.Return()
	return _c
}

func (_c *Writer_Warning_Call) RunAndReturn(run func(...interface{})) *Writer_Warning_Call {
	_c.Run(run)
	return _c
}

// Warningf provides a mock function with given fields: format, args
func (_m *Writer) Warningf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Writer_Warningf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warningf'
type Writer_Warningf_Call struct {
	*mock.Call
}

// Warningf is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *Writer_Expecter) Warningf(format interface{}, args ...interface{}) *Writer_Warningf_Call {
	return &Writer_Warningf_Call{Call: _e.mock.On("Warningf",
		append([]interface{}{format}, args...)...)}
}

func (_c *Writer_Warningf_Call) Run(run func(format string, args ...interface{})) *Writer_Warningf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *Writer_Warningf_Call) Return() *Writer_Warningf_Call {
	_c.Call.Return()
	return _c
}

func (_c *Writer_Warningf_Call) RunAndReturn(run func(string, ...interface{})) *Writer_Warningf_Call {
	_c.Run(run)
	return _c
}

// With provides a mock function with given fields: data
func (_m *Writer) With(data map[string]interface{}) log.Writer {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for With")
	}

	var r0 log.Writer
	if rf, ok := ret.Get(0).(func(map[string]interface{}) log.Writer); ok {
		r0 = rf(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(log.Writer)
		}
	}

	return r0
}

// Writer_With_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'With'
type Writer_With_Call struct {
	*mock.Call
}

// With is a helper method to define mock.On call
//   - data map[string]interface{}
func (_e *Writer_Expecter) With(data interface{}) *Writer_With_Call {
	return &Writer_With_Call{Call: _e.mock.On("With", data)}
}

func (_c *Writer_With_Call) Run(run func(data map[string]interface{})) *Writer_With_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string]interface{}))
	})
	return _c
}

func (_c *Writer_With_Call) Return(_a0 log.Writer) *Writer_With_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Writer_With_Call) RunAndReturn(run func(map[string]interface{}) log.Writer) *Writer_With_Call {
	_c.Call.Return(run)
	return _c
}

// WithTrace provides a mock function with no fields
func (_m *Writer) WithTrace() log.Writer {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for WithTrace")
	}

	var r0 log.Writer
	if rf, ok := ret.Get(0).(func() log.Writer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(log.Writer)
		}
	}

	return r0
}

// Writer_WithTrace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTrace'
type Writer_WithTrace_Call struct {
	*mock.Call
}

// WithTrace is a helper method to define mock.On call
func (_e *Writer_Expecter) WithTrace() *Writer_WithTrace_Call {
	return &Writer_WithTrace_Call{Call: _e.mock.On("WithTrace")}
}

func (_c *Writer_WithTrace_Call) Run(run func()) *Writer_WithTrace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Writer_WithTrace_Call) Return(_a0 log.Writer) *Writer_WithTrace_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Writer_WithTrace_Call) RunAndReturn(run func() log.Writer) *Writer_WithTrace_Call {
	_c.Call.Return(run)
	return _c
}

// NewWriter creates a new instance of Writer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Writer {
	mock := &Writer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
