// Code generated by mockery. DO NOT EDIT.

package client

import (
	http "net/http"

	client "github.com/goravel/framework/contracts/http/client"

	mock "github.com/stretchr/testify/mock"
)

// FakeResponse is an autogenerated mock type for the FakeResponse type
type FakeResponse struct {
	mock.Mock
}

type FakeResponse_Expecter struct {
	mock *mock.Mock
}

func (_m *FakeResponse) EXPECT() *FakeResponse_Expecter {
	return &FakeResponse_Expecter{mock: &_m.Mock}
}

// File provides a mock function with given fields: status, path
func (_m *FakeResponse) File(status int, path string) client.Response {
	ret := _m.Called(status, path)

	if len(ret) == 0 {
		panic("no return value specified for File")
	}

	var r0 client.Response
	if rf, ok := ret.Get(0).(func(int, string) client.Response); ok {
		r0 = rf(status, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Response)
		}
	}

	return r0
}

// FakeResponse_File_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'File'
type FakeResponse_File_Call struct {
	*mock.Call
}

// File is a helper method to define mock.On call
//   - status int
//   - path string
func (_e *FakeResponse_Expecter) File(status interface{}, path interface{}) *FakeResponse_File_Call {
	return &FakeResponse_File_Call{Call: _e.mock.On("File", status, path)}
}

func (_c *FakeResponse_File_Call) Run(run func(status int, path string)) *FakeResponse_File_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(string))
	})
	return _c
}

func (_c *FakeResponse_File_Call) Return(_a0 client.Response) *FakeResponse_File_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FakeResponse_File_Call) RunAndReturn(run func(int, string) client.Response) *FakeResponse_File_Call {
	_c.Call.Return(run)
	return _c
}

// Json provides a mock function with given fields: code, obj
func (_m *FakeResponse) Json(code int, obj interface{}) client.Response {
	ret := _m.Called(code, obj)

	if len(ret) == 0 {
		panic("no return value specified for Json")
	}

	var r0 client.Response
	if rf, ok := ret.Get(0).(func(int, interface{}) client.Response); ok {
		r0 = rf(code, obj)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Response)
		}
	}

	return r0
}

// FakeResponse_Json_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Json'
type FakeResponse_Json_Call struct {
	*mock.Call
}

// Json is a helper method to define mock.On call
//   - code int
//   - obj interface{}
func (_e *FakeResponse_Expecter) Json(code interface{}, obj interface{}) *FakeResponse_Json_Call {
	return &FakeResponse_Json_Call{Call: _e.mock.On("Json", code, obj)}
}

func (_c *FakeResponse_Json_Call) Run(run func(code int, obj interface{})) *FakeResponse_Json_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(interface{}))
	})
	return _c
}

func (_c *FakeResponse_Json_Call) Return(_a0 client.Response) *FakeResponse_Json_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FakeResponse_Json_Call) RunAndReturn(run func(int, interface{}) client.Response) *FakeResponse_Json_Call {
	_c.Call.Return(run)
	return _c
}

// Make provides a mock function with given fields: status, body, header
func (_m *FakeResponse) Make(status int, body string, header http.Header) client.Response {
	ret := _m.Called(status, body, header)

	if len(ret) == 0 {
		panic("no return value specified for Make")
	}

	var r0 client.Response
	if rf, ok := ret.Get(0).(func(int, string, http.Header) client.Response); ok {
		r0 = rf(status, body, header)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Response)
		}
	}

	return r0
}

// FakeResponse_Make_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Make'
type FakeResponse_Make_Call struct {
	*mock.Call
}

// Make is a helper method to define mock.On call
//   - status int
//   - body string
//   - header http.Header
func (_e *FakeResponse_Expecter) Make(status interface{}, body interface{}, header interface{}) *FakeResponse_Make_Call {
	return &FakeResponse_Make_Call{Call: _e.mock.On("Make", status, body, header)}
}

func (_c *FakeResponse_Make_Call) Run(run func(status int, body string, header http.Header)) *FakeResponse_Make_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(string), args[2].(http.Header))
	})
	return _c
}

func (_c *FakeResponse_Make_Call) Return(_a0 client.Response) *FakeResponse_Make_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FakeResponse_Make_Call) RunAndReturn(run func(int, string, http.Header) client.Response) *FakeResponse_Make_Call {
	_c.Call.Return(run)
	return _c
}

// OK provides a mock function with no fields
func (_m *FakeResponse) OK() client.Response {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for OK")
	}

	var r0 client.Response
	if rf, ok := ret.Get(0).(func() client.Response); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Response)
		}
	}

	return r0
}

// FakeResponse_OK_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OK'
type FakeResponse_OK_Call struct {
	*mock.Call
}

// OK is a helper method to define mock.On call
func (_e *FakeResponse_Expecter) OK() *FakeResponse_OK_Call {
	return &FakeResponse_OK_Call{Call: _e.mock.On("OK")}
}

func (_c *FakeResponse_OK_Call) Run(run func()) *FakeResponse_OK_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FakeResponse_OK_Call) Return(_a0 client.Response) *FakeResponse_OK_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FakeResponse_OK_Call) RunAndReturn(run func() client.Response) *FakeResponse_OK_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function with given fields: code
func (_m *FakeResponse) Status(code int) client.Response {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 client.Response
	if rf, ok := ret.Get(0).(func(int) client.Response); ok {
		r0 = rf(code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Response)
		}
	}

	return r0
}

// FakeResponse_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type FakeResponse_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - code int
func (_e *FakeResponse_Expecter) Status(code interface{}) *FakeResponse_Status_Call {
	return &FakeResponse_Status_Call{Call: _e.mock.On("Status", code)}
}

func (_c *FakeResponse_Status_Call) Run(run func(code int)) *FakeResponse_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *FakeResponse_Status_Call) Return(_a0 client.Response) *FakeResponse_Status_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FakeResponse_Status_Call) RunAndReturn(run func(int) client.Response) *FakeResponse_Status_Call {
	_c.Call.Return(run)
	return _c
}

// String provides a mock function with given fields: status, body
func (_m *FakeResponse) String(status int, body string) client.Response {
	ret := _m.Called(status, body)

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 client.Response
	if rf, ok := ret.Get(0).(func(int, string) client.Response); ok {
		r0 = rf(status, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Response)
		}
	}

	return r0
}

// FakeResponse_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type FakeResponse_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
//   - status int
//   - body string
func (_e *FakeResponse_Expecter) String(status interface{}, body interface{}) *FakeResponse_String_Call {
	return &FakeResponse_String_Call{Call: _e.mock.On("String", status, body)}
}

func (_c *FakeResponse_String_Call) Run(run func(status int, body string)) *FakeResponse_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(string))
	})
	return _c
}

func (_c *FakeResponse_String_Call) Return(_a0 client.Response) *FakeResponse_String_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FakeResponse_String_Call) RunAndReturn(run func(int, string) client.Response) *FakeResponse_String_Call {
	_c.Call.Return(run)
	return _c
}

// NewFakeResponse creates a new instance of FakeResponse. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFakeResponse(t interface {
	mock.TestingT
	Cleanup(func())
}) *FakeResponse {
	mock := &FakeResponse{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
