// Code generated by mockery. DO NOT EDIT.

package http

import (
	http "github.com/goravel/framework/contracts/http"
	mock "github.com/stretchr/testify/mock"
)

// FormRequestWithAttributes is an autogenerated mock type for the FormRequestWithAttributes type
type FormRequestWithAttributes struct {
	mock.Mock
}

type FormRequestWithAttributes_Expecter struct {
	mock *mock.Mock
}

func (_m *FormRequestWithAttributes) EXPECT() *FormRequestWithAttributes_Expecter {
	return &FormRequestWithAttributes_Expecter{mock: &_m.Mock}
}

// Attributes provides a mock function with given fields: ctx
func (_m *FormRequestWithAttributes) Attributes(ctx http.Context) map[string]string {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Attributes")
	}

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func(http.Context) map[string]string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	return r0
}

// FormRequestWithAttributes_Attributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Attributes'
type FormRequestWithAttributes_Attributes_Call struct {
	*mock.Call
}

// Attributes is a helper method to define mock.On call
//   - ctx http.Context
func (_e *FormRequestWithAttributes_Expecter) Attributes(ctx interface{}) *FormRequestWithAttributes_Attributes_Call {
	return &FormRequestWithAttributes_Attributes_Call{Call: _e.mock.On("Attributes", ctx)}
}

func (_c *FormRequestWithAttributes_Attributes_Call) Run(run func(ctx http.Context)) *FormRequestWithAttributes_Attributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.Context))
	})
	return _c
}

func (_c *FormRequestWithAttributes_Attributes_Call) Return(_a0 map[string]string) *FormRequestWithAttributes_Attributes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FormRequestWithAttributes_Attributes_Call) RunAndReturn(run func(http.Context) map[string]string) *FormRequestWithAttributes_Attributes_Call {
	_c.Call.Return(run)
	return _c
}

// NewFormRequestWithAttributes creates a new instance of FormRequestWithAttributes. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFormRequestWithAttributes(t interface {
	mock.TestingT
	Cleanup(func())
}) *FormRequestWithAttributes {
	mock := &FormRequestWithAttributes{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
