// Code generated by mockery. DO NOT EDIT.

package http

import (
	http "github.com/goravel/framework/contracts/http"
	mock "github.com/stretchr/testify/mock"
)

// Middleware is an autogenerated mock type for the Middleware type
type Middleware struct {
	mock.Mock
}

type Middleware_Expecter struct {
	mock *mock.Mock
}

func (_m *Middleware) EXPECT() *Middleware_Expecter {
	return &Middleware_Expecter{mock: &_m.Mock}
}

// ServeHTTP provides a mock function with given fields: ctx
func (_m *Middleware) ServeHTTP(ctx http.Context) http.Response {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ServeHTTP")
	}

	var r0 http.Response
	if rf, ok := ret.Get(0).(func(http.Context) http.Response); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Response)
		}
	}

	return r0
}

// Middleware_ServeHTTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServeHTTP'
type Middleware_ServeHTTP_Call struct {
	*mock.Call
}

// ServeHTTP is a helper method to define mock.On call
//   - ctx http.Context
func (_e *Middleware_Expecter) ServeHTTP(ctx interface{}) *Middleware_ServeHTTP_Call {
	return &Middleware_ServeHTTP_Call{Call: _e.mock.On("ServeHTTP", ctx)}
}

func (_c *Middleware_ServeHTTP_Call) Run(run func(ctx http.Context)) *Middleware_ServeHTTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.Context))
	})
	return _c
}

func (_c *Middleware_ServeHTTP_Call) Return(_a0 http.Response) *Middleware_ServeHTTP_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Middleware_ServeHTTP_Call) RunAndReturn(run func(http.Context) http.Response) *Middleware_ServeHTTP_Call {
	_c.Call.Return(run)
	return _c
}

// NewMiddleware creates a new instance of Middleware. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMiddleware(t interface {
	mock.TestingT
	Cleanup(func())
}) *Middleware {
	mock := &Middleware{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
