// Code generated by mockery v2.34.2. DO NOT EDIT.

package mocks

import (
	console "github.com/goravel/framework/contracts/console"
	mock "github.com/stretchr/testify/mock"
)

// Artisan is an autogenerated mock type for the Artisan type
type Artisan struct {
	mock.Mock
}

// Call provides a mock function with given fields: command
func (_m *Artisan) Call(command string) {
	_m.Called(command)
}

// CallAndExit provides a mock function with given fields: command
func (_m *Artisan) CallAndExit(command string) {
	_m.Called(command)
}

// Register provides a mock function with given fields: commands
func (_m *Artisan) Register(commands []console.Command) {
	_m.Called(commands)
}

// Run provides a mock function with given fields: args, exitIfArtisan
func (_m *Artisan) Run(args []string, exitIfArtisan bool) {
	_m.Called(args, exitIfArtisan)
}

// NewArtisan creates a new instance of Artisan. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewArtisan(t interface {
	mock.TestingT
	Cleanup(func())
}) *Artisan {
	mock := &Artisan{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
