package pluralizer

import "github.com/goravel/framework/contracts/support/pluralizer"

var _ pluralizer.Language = (*EnglishLanguage)(nil)

type EnglishLanguage struct {
	singularRuleset pluralizer.Ruleset
	pluralRuleset   pluralizer.Ruleset
}

func NewEnglishLanguage() *EnglishLanguage {
	return &EnglishLanguage{
		singularRuleset: newEnglishSingularRuleset(),
		pluralRuleset:   newEnglishPluralRuleset(),
	}
}

func (r *EnglishLanguage) Name() string {
	return "english"
}

func (r *EnglishLanguage) SingularRuleset() pluralizer.Ruleset {
	return r.singularRuleset
}

func (r *EnglishLanguage) PluralRuleset() pluralizer.Ruleset {
	return r.pluralRuleset
}

func newEnglishPluralRuleset() pluralizer.Ruleset {
	uninflected := getUninflectedDefault()
	uninflected = append(uninflected,
		NewPattern(`(?i)people$`),
		NewPattern(`(?i)trivia$`),
		NewPattern(`(?i)\w+ware$`),
		NewPattern(`(?i)media$`),
	)

	irregular := pluralizer.Substitutions{
		NewSubstitution("abuse", "abuses"),
		NewSubstitution("atlas", "atlases"),
		NewSubstitution("avalanche", "avalanches"),
		NewSubstitution("axis", "axes"),
		NewSubstitution("axe", "axes"),
		NewSubstitution("beef", "beefs"),
		NewSubstitution("blouse", "blouses"),
		NewSubstitution("brother", "brothers"),
		NewSubstitution("brownie", "brownies"),
		NewSubstitution("cache", "caches"),
		NewSubstitution("cafe", "cafes"),
		NewSubstitution("canvas", "canvases"),
		NewSubstitution("cave", "caves"),
		NewSubstitution("chateau", "chateaux"),
		NewSubstitution("child", "children"),
		NewSubstitution("cookie", "cookies"),
		NewSubstitution("corpus", "corpuses"),
		NewSubstitution("cow", "cows"),
		NewSubstitution("criterion", "criteria"),
		NewSubstitution("curriculum", "curricula"),
		NewSubstitution("curve", "curves"),
		NewSubstitution("demo", "demos"),
		NewSubstitution("domino", "dominoes"),
		NewSubstitution("echo", "echoes"),
		NewSubstitution("emphasis", "emphases"),
		NewSubstitution("epoch", "epochs"),
		NewSubstitution("foe", "foes"),
		NewSubstitution("foot", "feet"),
		NewSubstitution("fungus", "fungi"),
		NewSubstitution("ganglion", "ganglions"),
		NewSubstitution("gas", "gases"),
		NewSubstitution("genie", "genies"),
		NewSubstitution("genus", "genera"),
		NewSubstitution("goose", "geese"),
		NewSubstitution("graffito", "graffiti"),
		NewSubstitution("grave", "graves"),
		NewSubstitution("hippopotamus", "hippopotami"),
		NewSubstitution("hoax", "hoaxes"),
		NewSubstitution("hoof", "hoofs"),
		NewSubstitution("human", "humans"),
		NewSubstitution("iris", "irises"),
		NewSubstitution("larva", "larvae"),
		NewSubstitution("leaf", "leaves"),
		NewSubstitution("lens", "lenses"),
		NewSubstitution("loaf", "loaves"),
		//NewSubstitution("louse", "lice"),
		NewSubstitution("man", "men"),
		NewSubstitution("medium", "media"),
		NewSubstitution("memorandum", "memoranda"),
		NewSubstitution("money", "monies"),
		NewSubstitution("mongoose", "mongooses"),
		NewSubstitution("motto", "mottoes"),
		//NewSubstitution("mouse", "mice"),
		NewSubstitution("move", "moves"),
		NewSubstitution("mythos", "mythoi"),
		NewSubstitution("neurosis", "neuroses"),
		NewSubstitution("niche", "niches"),
		NewSubstitution("niveau", "niveaux"),
		NewSubstitution("nucleus", "nuclei"),
		NewSubstitution("numen", "numina"),
		NewSubstitution("oasis", "oases"),
		NewSubstitution("occiput", "occiputs"),
		NewSubstitution("octopus", "octopuses"),
		NewSubstitution("opus", "opuses"),
		NewSubstitution("ox", "oxen"),
		NewSubstitution("passerby", "passersby"),
		NewSubstitution("penis", "penises"),
		NewSubstitution("person", "people"),
		NewSubstitution("plateau", "plateaux"),
		NewSubstitution("runner-up", "runners-up"),
		NewSubstitution("safe", "safes"),
		NewSubstitution("save", "saves"),
		NewSubstitution("sex", "sexes"),
		NewSubstitution("sieve", "sieves"),
		NewSubstitution("soliloquy", "soliloquies"),
		NewSubstitution("son-in-law", "sons-in-law"),
		NewSubstitution("stadium", "stadiums"),
		NewSubstitution("syllabus", "syllabi"),
		NewSubstitution("testis", "testes"),
		NewSubstitution("thief", "thieves"),
		NewSubstitution("tooth", "teeth"),
		NewSubstitution("tornado", "tornadoes"),
		NewSubstitution("trilby", "trilbys"),
		NewSubstitution("turf", "turfs"),
		NewSubstitution("valve", "valves"),
		NewSubstitution("volcano", "volcanoes"),
		NewSubstitution("wave", "waves"),
		NewSubstitution("zombie", "zombies"),
	}

	regular := pluralizer.Transformations{
		NewTransformation(`(?i)(s)tatus$`, `${1}tatuses`),
		NewTransformation(`(?i)(quiz)$`, `${1}zes`),
		NewTransformation(`(?i)^(ox)$`, `${1}en`),
		NewTransformation(`(?i)([ml])ouse$`, `${1}ice`),
		NewTransformation(`(?i)(matr|vert|ind)(ix|ex)$`, `${1}ices`),
		NewTransformation(`(?i)(x|ch|ss|sh)$`, `${1}es`),
		NewTransformation(`(?i)([^aeiouy]|qu)y$`, `${1}ies`),
		NewTransformation(`(?i)(hive|gulf)$`, `${1}s`),
		NewTransformation(`(?i)(?:([^f])fe|([lr])f)$`, `${1}${2}ves`),
		NewTransformation(`(?i)sis$`, `ses`),
		NewTransformation(`(?i)([ti])um$`, `${1}a`),
		NewTransformation(`(?i)(tax)on$`, `${1}a`),
		NewTransformation(`(?i)(c)riterion$`, `${1}riteria`),
		NewTransformation(`(?i)(p)erson$`, `${1}eople`),
		NewTransformation(`(?i)(m)an$`, `${1}en`),
		NewTransformation(`(?i)(c)hild$`, `${1}hildren`),
		NewTransformation(`(?i)(f)oot$`, `${1}eet`),
		NewTransformation(`(?i)(buffal|her|potat|tomat|volcan)o$`, `${1}oes`),
		NewTransformation(`(?i)(alumn|bacill|cact|foc|fung|nucle|radi|stimul|syllab|termin|vir)us$`, `${1}i`),
		NewTransformation(`(?i)us$`, `uses`),
		NewTransformation(`(?i)(alias)$`, `${1}es`),
		NewTransformation(`(?i)(analys|ax|cris|test|thes)is$`, `${1}es`),
		NewTransformation(`(?i)s$`, `s`),
		NewTransformation(`(?i)^$`, ``),
		NewTransformation(`(?i)$`, `s`),
	}

	return NewRuleset(regular, uninflected, irregular)
}

func newEnglishSingularRuleset() pluralizer.Ruleset {
	uninflected := getUninflectedDefault()
	uninflected = append(uninflected,
		NewPattern(`(?i).*ss$`),
		NewPattern(`(?i)clothes$`),
		NewPattern(`(?i)data$`),
		NewPattern(`(?i)fascia$`),
		NewPattern(`(?i)fuchsia$`),
		NewPattern(`(?i)galleria$`),
		NewPattern(`(?i)mafia$`),
		NewPattern(`(?i)militia$`),
		NewPattern(`(?i)pants$`),
		NewPattern(`(?i)petunia$`),
		NewPattern(`(?i)sepia$`),
		NewPattern(`(?i)trivia$`),
		NewPattern(`(?i)utopia$`),
	)

	irregular := pluralizer.Substitutions{}
	for _, sub := range newEnglishPluralRuleset().Irregular() {
		irregular = append(irregular, NewSubstitution(sub.To(), sub.From()))
	}

	regular := pluralizer.Transformations{
		NewTransformation(`(?i)(s)tatuses$`, `${1}tatus`),
		NewTransformation(`(?i)(s)tatus$`, `${1}tatus`),
		NewTransformation(`(?i)(c)ampus$`, `${1}ampus`),
		NewTransformation(`(?i)^(.*)(menu)s$`, `${1}${2}`),
		NewTransformation(`(?i)(quiz)zes$`, `${1}`),
		NewTransformation(`(?i)(matr)ices$`, `${1}ix`),
		NewTransformation(`(?i)(vert|ind)ices$`, `${1}ex`),
		NewTransformation(`(?i)^(ox)en`, `${1}`),
		NewTransformation(`(?i)(alias)(es)*$`, `${1}`),
		NewTransformation(`(?i)(buffal|her|potat|tomat|volcan)oes$`, `${1}o`),
		NewTransformation(`(?i)(alumn|bacill|cact|foc|fung|nucle|radi|stimul|syllab|termin|viri?)i$`, `${1}us`),
		NewTransformation(`(?i)([ftw]ax)es$`, `${1}`),
		NewTransformation(`(?i)(analys|ax|cris|test|thes)es$`, `${1}is`),
		NewTransformation(`(?i)(shoe|slave)s$`, `${1}`),
		NewTransformation(`(?i)(o)es$`, `${1}`),
		NewTransformation(`(?i)ouses$`, `ouse`),
		NewTransformation(`(?i)([^a])uses$`, `${1}us`),
		NewTransformation(`(?i)([ml])ice$`, `${1}ouse`),
		NewTransformation(`(?i)(x|ch|ss|sh)es$`, `${1}`),
		NewTransformation(`(?i)(m)ovies$`, `${1}ovie`),
		NewTransformation(`(?i)(s)eries$`, `${1}eries`),
		NewTransformation(`(?i)([^aeiouy]|qu)ies$`, `${1}y`),
		NewTransformation(`(?i)([lr])ves$`, `${1}f`),
		NewTransformation(`(?i)(tive)s$`, `${1}`),
		NewTransformation(`(?i)(hive)s$`, `${1}`),
		NewTransformation(`(?i)(drive)s$`, `${1}`),
		NewTransformation(`(?i)(dive)s$`, `${1}`),
		NewTransformation(`(?i)(olive)s$`, `${1}`),
		NewTransformation(`(?i)([^fo])ves$`, `${1}fe`),
		NewTransformation(`(?i)(^analy)ses$`, `${1}sis`),
		NewTransformation(`(?i)(analy|diagno|^ba|(p)arenthe|(p)rogno|(s)ynop|(t)he)ses$`, `${1}${2}sis`),
		NewTransformation(`(?i)(tax)a$`, `${1}on`),
		NewTransformation(`(?i)(c)riteria$`, `${1}riterion`),
		NewTransformation(`(?i)([ti])a$`, `${1}um`),
		NewTransformation(`(?i)(p)eople$`, `${1}erson`),
		NewTransformation(`(?i)(m)en$`, `${1}an`),
		NewTransformation(`(?i)(c)hildren$`, `${1}hild`),
		NewTransformation(`(?i)(f)eet$`, `${1}oot`),
		NewTransformation(`(?i)(n)ews$`, `${1}ews`),
		NewTransformation(`(?i)eaus$`, `eau`),
		NewTransformation(`(?i)^tights$`, `tights`),
		NewTransformation(`(?i)^shorts$`, `shorts`),
		NewTransformation(`(?i)s$`, ``),
	}

	return NewRuleset(regular, uninflected, irregular)
}

func getUninflectedDefault() []pluralizer.Pattern {
	return []pluralizer.Pattern{
		NewPattern(`(?i)\w+media$`),
		NewPattern(`(?i)advice$`),
		NewPattern(`(?i)aircraft$`),
		NewPattern(`(?i)amoyese$`),
		NewPattern(`(?i)art$`),
		NewPattern(`(?i)audio$`),
		NewPattern(`(?i)baggage$`),
		NewPattern(`(?i)bison$`),
		NewPattern(`(?i)borghese$`),
		NewPattern(`(?i)bream$`),
		NewPattern(`(?i)breeches$`),
		NewPattern(`(?i)britches$`),
		NewPattern(`(?i)buffalo$`),
		NewPattern(`(?i)butter$`),
		NewPattern(`(?i)cantus$`),
		NewPattern(`(?i)carp$`),
		NewPattern(`(?i)cattle$`),
		NewPattern(`(?i)chassis$`),
		NewPattern(`(?i)clippers$`),
		NewPattern(`(?i)clothing$`),
		NewPattern(`(?i)coal$`),
		NewPattern(`(?i)cod$`),
		NewPattern(`(?i)coitus$`),
		NewPattern(`(?i)compensation$`),
		NewPattern(`(?i)congoese$`),
		NewPattern(`(?i)contretemps$`),
		NewPattern(`(?i)coreopsis$`),
		NewPattern(`(?i)corps$`),
		NewPattern(`(?i)cotton$`),
		NewPattern(`(?i)data$`),
		NewPattern(`(?i)debris$`),
		NewPattern(`(?i)deer$`),
		NewPattern(`(?i)diabetes$`),
		NewPattern(`(?i)djinn$`),
		NewPattern(`(?i)education$`),
		NewPattern(`(?i)eland$`),
		NewPattern(`(?i)elk$`),
		NewPattern(`(?i)emoji$`),
		NewPattern(`(?i)equipment$`),
		NewPattern(`(?i)evidence$`),
		NewPattern(`(?i)faroese$`),
		NewPattern(`(?i)feedback$`),
		NewPattern(`(?i)fish$`),
		NewPattern(`(?i)flounder$`),
		NewPattern(`(?i)flour$`),
		NewPattern(`(?i)foochowese$`),
		NewPattern(`(?i)food$`),
		NewPattern(`(?i)furniture$`),
		NewPattern(`(?i)gallows$`),
		NewPattern(`(?i)genevese$`),
		NewPattern(`(?i)genoese$`),
		NewPattern(`(?i)gilbertese$`),
		NewPattern(`(?i)gold$`),
		NewPattern(`(?i)headquarters$`),
		NewPattern(`(?i)herpes$`),
		NewPattern(`(?i)hijinks$`),
		NewPattern(`(?i)homework$`),
		NewPattern(`(?i)hottentotese$`),
		NewPattern(`(?i)impatience$`),
		NewPattern(`(?i)information$`),
		NewPattern(`(?i)innings$`),
		NewPattern(`(?i)jackanapes$`),
		NewPattern(`(?i)jeans$`),
		NewPattern(`(?i)jedi$`),
		NewPattern(`(?i)kin$`),
		NewPattern(`(?i)kiplingese$`),
		NewPattern(`(?i)knowledge$`),
		NewPattern(`(?i)kongoese$`),
		NewPattern(`(?i)leather$`),
		NewPattern(`(?i)love$`),
		NewPattern(`(?i)lucchese$`),
		NewPattern(`(?i)luggage$`),
		NewPattern(`(?i)mackerel$`),
		NewPattern(`(?i)Maltese$`),
		NewPattern(`(?i)management$`),
		NewPattern(`(?i)metadata$`),
		NewPattern(`(?i)mews$`),
		NewPattern(`(?i)money$`),
		NewPattern(`(?i)moose$`),
		NewPattern(`(?i)mumps$`),
		NewPattern(`(?i)music$`),
		NewPattern(`(?i)nankingese$`),
		NewPattern(`(?i)news$`),
		NewPattern(`(?i)nexus$`),
		NewPattern(`(?i)niasese$`),
		NewPattern(`(?i)nutrition$`),
		NewPattern(`(?i)offspring$`),
		NewPattern(`(?i)oil$`),
		NewPattern(`(?i)patience$`),
		NewPattern(`(?i)pekingese$`),
		NewPattern(`(?i)piedmontese$`),
		NewPattern(`(?i)pincers$`),
		NewPattern(`(?i)pistoiese$`),
		NewPattern(`(?i)plankton$`),
		NewPattern(`(?i)pliers$`),
		NewPattern(`(?i)pokemon$`),
		NewPattern(`(?i)police$`),
		NewPattern(`(?i)polish$`),
		NewPattern(`(?i)portuguese$`),
		NewPattern(`(?i)proceedings$`),
		NewPattern(`(?i)progress$`),
		NewPattern(`(?i)rabies$`),
		NewPattern(`(?i)rain$`),
		NewPattern(`(?i)research$`),
		NewPattern(`(?i)rhinoceros$`),
		NewPattern(`(?i)rice$`),
		NewPattern(`(?i)salmon$`),
		NewPattern(`(?i)sand$`),
		NewPattern(`(?i)sarawakese$`),
		NewPattern(`(?i)scissors$`),
		NewPattern(`(?i)sea[- ]bass$`),
		NewPattern(`(?i)series$`),
		NewPattern(`(?i)shavese$`),
		NewPattern(`(?i)shears$`),
		NewPattern(`(?i)sheep$`),
		NewPattern(`(?i)siemens$`),
		NewPattern(`(?i)silk$`),
		NewPattern(`(?i)sms$`),
		NewPattern(`(?i)soap$`),
		NewPattern(`(?i)social media$`),
		NewPattern(`(?i)spam$`),
		NewPattern(`(?i)species$`),
		NewPattern(`(?i)staff$`),
		NewPattern(`(?i)sugar$`),
		NewPattern(`(?i)swine$`),
		NewPattern(`(?i)talent$`),
		NewPattern(`(?i)toothpaste$`),
		NewPattern(`(?i)traffic$`),
		NewPattern(`(?i)travel$`),
		NewPattern(`(?i)trousers$`),
		NewPattern(`(?i)trout$`),
		NewPattern(`(?i)tuna$`),
		NewPattern(`(?i)us$`),
		NewPattern(`(?i)vermontese$`),
		NewPattern(`(?i)vinegar$`),
		NewPattern(`(?i)weather$`),
		NewPattern(`(?i)wenchowese$`),
		NewPattern(`(?i)wheat$`),
		NewPattern(`(?i)whiting$`),
		NewPattern(`(?i)wildebeest$`),
		NewPattern(`(?i)wood$`),
		NewPattern(`(?i)wool$`),
		NewPattern(`(?i)yengeese$`),
	}
}
