// Code generated by mockery. DO NOT EDIT.

package orm

import (
	orm "github.com/goravel/framework/contracts/database/orm"
	mock "github.com/stretchr/testify/mock"
)

// QueryWithRelations is an autogenerated mock type for the QueryWithRelations type
type QueryWithRelations struct {
	mock.Mock
}

type QueryWithRelations_Expecter struct {
	mock *mock.Mock
}

func (_m *QueryWithRelations) EXPECT() *QueryWithRelations_Expecter {
	return &QueryWithRelations_Expecter{mock: &_m.Mock}
}

// DoesntHave provides a mock function with given fields: relation, args
func (_m *QueryWithRelations) DoesntHave(relation string, args ...interface{}) orm.Query {
	var _ca []interface{}
	_ca = append(_ca, relation)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DoesntHave")
	}

	var r0 orm.Query
	if rf, ok := ret.Get(0).(func(string, ...interface{}) orm.Query); ok {
		r0 = rf(relation, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(orm.Query)
		}
	}

	return r0
}

// QueryWithRelations_DoesntHave_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoesntHave'
type QueryWithRelations_DoesntHave_Call struct {
	*mock.Call
}

// DoesntHave is a helper method to define mock.On call
//   - relation string
//   - args ...interface{}
func (_e *QueryWithRelations_Expecter) DoesntHave(relation interface{}, args ...interface{}) *QueryWithRelations_DoesntHave_Call {
	return &QueryWithRelations_DoesntHave_Call{Call: _e.mock.On("DoesntHave",
		append([]interface{}{relation}, args...)...)}
}

func (_c *QueryWithRelations_DoesntHave_Call) Run(run func(relation string, args ...interface{})) *QueryWithRelations_DoesntHave_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *QueryWithRelations_DoesntHave_Call) Return(_a0 orm.Query) *QueryWithRelations_DoesntHave_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryWithRelations_DoesntHave_Call) RunAndReturn(run func(string, ...interface{}) orm.Query) *QueryWithRelations_DoesntHave_Call {
	_c.Call.Return(run)
	return _c
}

// DoesntHaveMorph provides a mock function with given fields: relation, types, args
func (_m *QueryWithRelations) DoesntHaveMorph(relation string, types []interface{}, args ...interface{}) orm.Query {
	var _ca []interface{}
	_ca = append(_ca, relation, types)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DoesntHaveMorph")
	}

	var r0 orm.Query
	if rf, ok := ret.Get(0).(func(string, []interface{}, ...interface{}) orm.Query); ok {
		r0 = rf(relation, types, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(orm.Query)
		}
	}

	return r0
}

// QueryWithRelations_DoesntHaveMorph_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoesntHaveMorph'
type QueryWithRelations_DoesntHaveMorph_Call struct {
	*mock.Call
}

// DoesntHaveMorph is a helper method to define mock.On call
//   - relation string
//   - types []interface{}
//   - args ...interface{}
func (_e *QueryWithRelations_Expecter) DoesntHaveMorph(relation interface{}, types interface{}, args ...interface{}) *QueryWithRelations_DoesntHaveMorph_Call {
	return &QueryWithRelations_DoesntHaveMorph_Call{Call: _e.mock.On("DoesntHaveMorph",
		append([]interface{}{relation, types}, args...)...)}
}

func (_c *QueryWithRelations_DoesntHaveMorph_Call) Run(run func(relation string, types []interface{}, args ...interface{})) *QueryWithRelations_DoesntHaveMorph_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), args[1].([]interface{}), variadicArgs...)
	})
	return _c
}

func (_c *QueryWithRelations_DoesntHaveMorph_Call) Return(_a0 orm.Query) *QueryWithRelations_DoesntHaveMorph_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryWithRelations_DoesntHaveMorph_Call) RunAndReturn(run func(string, []interface{}, ...interface{}) orm.Query) *QueryWithRelations_DoesntHaveMorph_Call {
	_c.Call.Return(run)
	return _c
}

// Has provides a mock function with given fields: relation, args
func (_m *QueryWithRelations) Has(relation string, args ...interface{}) orm.Query {
	var _ca []interface{}
	_ca = append(_ca, relation)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Has")
	}

	var r0 orm.Query
	if rf, ok := ret.Get(0).(func(string, ...interface{}) orm.Query); ok {
		r0 = rf(relation, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(orm.Query)
		}
	}

	return r0
}

// QueryWithRelations_Has_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Has'
type QueryWithRelations_Has_Call struct {
	*mock.Call
}

// Has is a helper method to define mock.On call
//   - relation string
//   - args ...interface{}
func (_e *QueryWithRelations_Expecter) Has(relation interface{}, args ...interface{}) *QueryWithRelations_Has_Call {
	return &QueryWithRelations_Has_Call{Call: _e.mock.On("Has",
		append([]interface{}{relation}, args...)...)}
}

func (_c *QueryWithRelations_Has_Call) Run(run func(relation string, args ...interface{})) *QueryWithRelations_Has_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *QueryWithRelations_Has_Call) Return(_a0 orm.Query) *QueryWithRelations_Has_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryWithRelations_Has_Call) RunAndReturn(run func(string, ...interface{}) orm.Query) *QueryWithRelations_Has_Call {
	_c.Call.Return(run)
	return _c
}

// HasMorph provides a mock function with given fields: relation, types, args
func (_m *QueryWithRelations) HasMorph(relation string, types []interface{}, args ...interface{}) orm.Query {
	var _ca []interface{}
	_ca = append(_ca, relation, types)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for HasMorph")
	}

	var r0 orm.Query
	if rf, ok := ret.Get(0).(func(string, []interface{}, ...interface{}) orm.Query); ok {
		r0 = rf(relation, types, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(orm.Query)
		}
	}

	return r0
}

// QueryWithRelations_HasMorph_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasMorph'
type QueryWithRelations_HasMorph_Call struct {
	*mock.Call
}

// HasMorph is a helper method to define mock.On call
//   - relation string
//   - types []interface{}
//   - args ...interface{}
func (_e *QueryWithRelations_Expecter) HasMorph(relation interface{}, types interface{}, args ...interface{}) *QueryWithRelations_HasMorph_Call {
	return &QueryWithRelations_HasMorph_Call{Call: _e.mock.On("HasMorph",
		append([]interface{}{relation, types}, args...)...)}
}

func (_c *QueryWithRelations_HasMorph_Call) Run(run func(relation string, types []interface{}, args ...interface{})) *QueryWithRelations_HasMorph_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), args[1].([]interface{}), variadicArgs...)
	})
	return _c
}

func (_c *QueryWithRelations_HasMorph_Call) Return(_a0 orm.Query) *QueryWithRelations_HasMorph_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryWithRelations_HasMorph_Call) RunAndReturn(run func(string, []interface{}, ...interface{}) orm.Query) *QueryWithRelations_HasMorph_Call {
	_c.Call.Return(run)
	return _c
}

// OrDoesntHave provides a mock function with given fields: relation, args
func (_m *QueryWithRelations) OrDoesntHave(relation string, args ...interface{}) orm.Query {
	var _ca []interface{}
	_ca = append(_ca, relation)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for OrDoesntHave")
	}

	var r0 orm.Query
	if rf, ok := ret.Get(0).(func(string, ...interface{}) orm.Query); ok {
		r0 = rf(relation, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(orm.Query)
		}
	}

	return r0
}

// QueryWithRelations_OrDoesntHave_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrDoesntHave'
type QueryWithRelations_OrDoesntHave_Call struct {
	*mock.Call
}

// OrDoesntHave is a helper method to define mock.On call
//   - relation string
//   - args ...interface{}
func (_e *QueryWithRelations_Expecter) OrDoesntHave(relation interface{}, args ...interface{}) *QueryWithRelations_OrDoesntHave_Call {
	return &QueryWithRelations_OrDoesntHave_Call{Call: _e.mock.On("OrDoesntHave",
		append([]interface{}{relation}, args...)...)}
}

func (_c *QueryWithRelations_OrDoesntHave_Call) Run(run func(relation string, args ...interface{})) *QueryWithRelations_OrDoesntHave_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *QueryWithRelations_OrDoesntHave_Call) Return(_a0 orm.Query) *QueryWithRelations_OrDoesntHave_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryWithRelations_OrDoesntHave_Call) RunAndReturn(run func(string, ...interface{}) orm.Query) *QueryWithRelations_OrDoesntHave_Call {
	_c.Call.Return(run)
	return _c
}

// OrDoesntHaveMorph provides a mock function with given fields: relation, types, args
func (_m *QueryWithRelations) OrDoesntHaveMorph(relation string, types []interface{}, args ...interface{}) orm.Query {
	var _ca []interface{}
	_ca = append(_ca, relation, types)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for OrDoesntHaveMorph")
	}

	var r0 orm.Query
	if rf, ok := ret.Get(0).(func(string, []interface{}, ...interface{}) orm.Query); ok {
		r0 = rf(relation, types, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(orm.Query)
		}
	}

	return r0
}

// QueryWithRelations_OrDoesntHaveMorph_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrDoesntHaveMorph'
type QueryWithRelations_OrDoesntHaveMorph_Call struct {
	*mock.Call
}

// OrDoesntHaveMorph is a helper method to define mock.On call
//   - relation string
//   - types []interface{}
//   - args ...interface{}
func (_e *QueryWithRelations_Expecter) OrDoesntHaveMorph(relation interface{}, types interface{}, args ...interface{}) *QueryWithRelations_OrDoesntHaveMorph_Call {
	return &QueryWithRelations_OrDoesntHaveMorph_Call{Call: _e.mock.On("OrDoesntHaveMorph",
		append([]interface{}{relation, types}, args...)...)}
}

func (_c *QueryWithRelations_OrDoesntHaveMorph_Call) Run(run func(relation string, types []interface{}, args ...interface{})) *QueryWithRelations_OrDoesntHaveMorph_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), args[1].([]interface{}), variadicArgs...)
	})
	return _c
}

func (_c *QueryWithRelations_OrDoesntHaveMorph_Call) Return(_a0 orm.Query) *QueryWithRelations_OrDoesntHaveMorph_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryWithRelations_OrDoesntHaveMorph_Call) RunAndReturn(run func(string, []interface{}, ...interface{}) orm.Query) *QueryWithRelations_OrDoesntHaveMorph_Call {
	_c.Call.Return(run)
	return _c
}

// OrHas provides a mock function with given fields: relation, args
func (_m *QueryWithRelations) OrHas(relation string, args ...interface{}) orm.Query {
	var _ca []interface{}
	_ca = append(_ca, relation)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for OrHas")
	}

	var r0 orm.Query
	if rf, ok := ret.Get(0).(func(string, ...interface{}) orm.Query); ok {
		r0 = rf(relation, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(orm.Query)
		}
	}

	return r0
}

// QueryWithRelations_OrHas_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrHas'
type QueryWithRelations_OrHas_Call struct {
	*mock.Call
}

// OrHas is a helper method to define mock.On call
//   - relation string
//   - args ...interface{}
func (_e *QueryWithRelations_Expecter) OrHas(relation interface{}, args ...interface{}) *QueryWithRelations_OrHas_Call {
	return &QueryWithRelations_OrHas_Call{Call: _e.mock.On("OrHas",
		append([]interface{}{relation}, args...)...)}
}

func (_c *QueryWithRelations_OrHas_Call) Run(run func(relation string, args ...interface{})) *QueryWithRelations_OrHas_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *QueryWithRelations_OrHas_Call) Return(_a0 orm.Query) *QueryWithRelations_OrHas_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryWithRelations_OrHas_Call) RunAndReturn(run func(string, ...interface{}) orm.Query) *QueryWithRelations_OrHas_Call {
	_c.Call.Return(run)
	return _c
}

// OrHasMorph provides a mock function with given fields: relation, types, args
func (_m *QueryWithRelations) OrHasMorph(relation string, types []interface{}, args ...interface{}) orm.Query {
	var _ca []interface{}
	_ca = append(_ca, relation, types)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for OrHasMorph")
	}

	var r0 orm.Query
	if rf, ok := ret.Get(0).(func(string, []interface{}, ...interface{}) orm.Query); ok {
		r0 = rf(relation, types, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(orm.Query)
		}
	}

	return r0
}

// QueryWithRelations_OrHasMorph_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrHasMorph'
type QueryWithRelations_OrHasMorph_Call struct {
	*mock.Call
}

// OrHasMorph is a helper method to define mock.On call
//   - relation string
//   - types []interface{}
//   - args ...interface{}
func (_e *QueryWithRelations_Expecter) OrHasMorph(relation interface{}, types interface{}, args ...interface{}) *QueryWithRelations_OrHasMorph_Call {
	return &QueryWithRelations_OrHasMorph_Call{Call: _e.mock.On("OrHasMorph",
		append([]interface{}{relation, types}, args...)...)}
}

func (_c *QueryWithRelations_OrHasMorph_Call) Run(run func(relation string, types []interface{}, args ...interface{})) *QueryWithRelations_OrHasMorph_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), args[1].([]interface{}), variadicArgs...)
	})
	return _c
}

func (_c *QueryWithRelations_OrHasMorph_Call) Return(_a0 orm.Query) *QueryWithRelations_OrHasMorph_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryWithRelations_OrHasMorph_Call) RunAndReturn(run func(string, []interface{}, ...interface{}) orm.Query) *QueryWithRelations_OrHasMorph_Call {
	_c.Call.Return(run)
	return _c
}

// OrWhereDoesntHave provides a mock function with given fields: relation, args
func (_m *QueryWithRelations) OrWhereDoesntHave(relation string, args ...interface{}) orm.Query {
	var _ca []interface{}
	_ca = append(_ca, relation)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for OrWhereDoesntHave")
	}

	var r0 orm.Query
	if rf, ok := ret.Get(0).(func(string, ...interface{}) orm.Query); ok {
		r0 = rf(relation, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(orm.Query)
		}
	}

	return r0
}

// QueryWithRelations_OrWhereDoesntHave_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrWhereDoesntHave'
type QueryWithRelations_OrWhereDoesntHave_Call struct {
	*mock.Call
}

// OrWhereDoesntHave is a helper method to define mock.On call
//   - relation string
//   - args ...interface{}
func (_e *QueryWithRelations_Expecter) OrWhereDoesntHave(relation interface{}, args ...interface{}) *QueryWithRelations_OrWhereDoesntHave_Call {
	return &QueryWithRelations_OrWhereDoesntHave_Call{Call: _e.mock.On("OrWhereDoesntHave",
		append([]interface{}{relation}, args...)...)}
}

func (_c *QueryWithRelations_OrWhereDoesntHave_Call) Run(run func(relation string, args ...interface{})) *QueryWithRelations_OrWhereDoesntHave_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *QueryWithRelations_OrWhereDoesntHave_Call) Return(_a0 orm.Query) *QueryWithRelations_OrWhereDoesntHave_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryWithRelations_OrWhereDoesntHave_Call) RunAndReturn(run func(string, ...interface{}) orm.Query) *QueryWithRelations_OrWhereDoesntHave_Call {
	_c.Call.Return(run)
	return _c
}

// OrWhereDoesntHaveMorph provides a mock function with given fields: relation, types, args
func (_m *QueryWithRelations) OrWhereDoesntHaveMorph(relation string, types []interface{}, args ...interface{}) orm.Query {
	var _ca []interface{}
	_ca = append(_ca, relation, types)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for OrWhereDoesntHaveMorph")
	}

	var r0 orm.Query
	if rf, ok := ret.Get(0).(func(string, []interface{}, ...interface{}) orm.Query); ok {
		r0 = rf(relation, types, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(orm.Query)
		}
	}

	return r0
}

// QueryWithRelations_OrWhereDoesntHaveMorph_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrWhereDoesntHaveMorph'
type QueryWithRelations_OrWhereDoesntHaveMorph_Call struct {
	*mock.Call
}

// OrWhereDoesntHaveMorph is a helper method to define mock.On call
//   - relation string
//   - types []interface{}
//   - args ...interface{}
func (_e *QueryWithRelations_Expecter) OrWhereDoesntHaveMorph(relation interface{}, types interface{}, args ...interface{}) *QueryWithRelations_OrWhereDoesntHaveMorph_Call {
	return &QueryWithRelations_OrWhereDoesntHaveMorph_Call{Call: _e.mock.On("OrWhereDoesntHaveMorph",
		append([]interface{}{relation, types}, args...)...)}
}

func (_c *QueryWithRelations_OrWhereDoesntHaveMorph_Call) Run(run func(relation string, types []interface{}, args ...interface{})) *QueryWithRelations_OrWhereDoesntHaveMorph_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), args[1].([]interface{}), variadicArgs...)
	})
	return _c
}

func (_c *QueryWithRelations_OrWhereDoesntHaveMorph_Call) Return(_a0 orm.Query) *QueryWithRelations_OrWhereDoesntHaveMorph_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryWithRelations_OrWhereDoesntHaveMorph_Call) RunAndReturn(run func(string, []interface{}, ...interface{}) orm.Query) *QueryWithRelations_OrWhereDoesntHaveMorph_Call {
	_c.Call.Return(run)
	return _c
}

// OrWhereHas provides a mock function with given fields: relation, args
func (_m *QueryWithRelations) OrWhereHas(relation string, args ...interface{}) orm.Query {
	var _ca []interface{}
	_ca = append(_ca, relation)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for OrWhereHas")
	}

	var r0 orm.Query
	if rf, ok := ret.Get(0).(func(string, ...interface{}) orm.Query); ok {
		r0 = rf(relation, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(orm.Query)
		}
	}

	return r0
}

// QueryWithRelations_OrWhereHas_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrWhereHas'
type QueryWithRelations_OrWhereHas_Call struct {
	*mock.Call
}

// OrWhereHas is a helper method to define mock.On call
//   - relation string
//   - args ...interface{}
func (_e *QueryWithRelations_Expecter) OrWhereHas(relation interface{}, args ...interface{}) *QueryWithRelations_OrWhereHas_Call {
	return &QueryWithRelations_OrWhereHas_Call{Call: _e.mock.On("OrWhereHas",
		append([]interface{}{relation}, args...)...)}
}

func (_c *QueryWithRelations_OrWhereHas_Call) Run(run func(relation string, args ...interface{})) *QueryWithRelations_OrWhereHas_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *QueryWithRelations_OrWhereHas_Call) Return(_a0 orm.Query) *QueryWithRelations_OrWhereHas_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryWithRelations_OrWhereHas_Call) RunAndReturn(run func(string, ...interface{}) orm.Query) *QueryWithRelations_OrWhereHas_Call {
	_c.Call.Return(run)
	return _c
}

// OrWhereHasMorph provides a mock function with given fields: relation, types, args
func (_m *QueryWithRelations) OrWhereHasMorph(relation string, types []interface{}, args ...interface{}) orm.Query {
	var _ca []interface{}
	_ca = append(_ca, relation, types)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for OrWhereHasMorph")
	}

	var r0 orm.Query
	if rf, ok := ret.Get(0).(func(string, []interface{}, ...interface{}) orm.Query); ok {
		r0 = rf(relation, types, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(orm.Query)
		}
	}

	return r0
}

// QueryWithRelations_OrWhereHasMorph_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrWhereHasMorph'
type QueryWithRelations_OrWhereHasMorph_Call struct {
	*mock.Call
}

// OrWhereHasMorph is a helper method to define mock.On call
//   - relation string
//   - types []interface{}
//   - args ...interface{}
func (_e *QueryWithRelations_Expecter) OrWhereHasMorph(relation interface{}, types interface{}, args ...interface{}) *QueryWithRelations_OrWhereHasMorph_Call {
	return &QueryWithRelations_OrWhereHasMorph_Call{Call: _e.mock.On("OrWhereHasMorph",
		append([]interface{}{relation, types}, args...)...)}
}

func (_c *QueryWithRelations_OrWhereHasMorph_Call) Run(run func(relation string, types []interface{}, args ...interface{})) *QueryWithRelations_OrWhereHasMorph_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), args[1].([]interface{}), variadicArgs...)
	})
	return _c
}

func (_c *QueryWithRelations_OrWhereHasMorph_Call) Return(_a0 orm.Query) *QueryWithRelations_OrWhereHasMorph_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryWithRelations_OrWhereHasMorph_Call) RunAndReturn(run func(string, []interface{}, ...interface{}) orm.Query) *QueryWithRelations_OrWhereHasMorph_Call {
	_c.Call.Return(run)
	return _c
}

// WhereDoesntHave provides a mock function with given fields: relation, args
func (_m *QueryWithRelations) WhereDoesntHave(relation string, args ...interface{}) orm.Query {
	var _ca []interface{}
	_ca = append(_ca, relation)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for WhereDoesntHave")
	}

	var r0 orm.Query
	if rf, ok := ret.Get(0).(func(string, ...interface{}) orm.Query); ok {
		r0 = rf(relation, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(orm.Query)
		}
	}

	return r0
}

// QueryWithRelations_WhereDoesntHave_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WhereDoesntHave'
type QueryWithRelations_WhereDoesntHave_Call struct {
	*mock.Call
}

// WhereDoesntHave is a helper method to define mock.On call
//   - relation string
//   - args ...interface{}
func (_e *QueryWithRelations_Expecter) WhereDoesntHave(relation interface{}, args ...interface{}) *QueryWithRelations_WhereDoesntHave_Call {
	return &QueryWithRelations_WhereDoesntHave_Call{Call: _e.mock.On("WhereDoesntHave",
		append([]interface{}{relation}, args...)...)}
}

func (_c *QueryWithRelations_WhereDoesntHave_Call) Run(run func(relation string, args ...interface{})) *QueryWithRelations_WhereDoesntHave_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *QueryWithRelations_WhereDoesntHave_Call) Return(_a0 orm.Query) *QueryWithRelations_WhereDoesntHave_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryWithRelations_WhereDoesntHave_Call) RunAndReturn(run func(string, ...interface{}) orm.Query) *QueryWithRelations_WhereDoesntHave_Call {
	_c.Call.Return(run)
	return _c
}

// WhereDoesntHaveMorph provides a mock function with given fields: relation, types, args
func (_m *QueryWithRelations) WhereDoesntHaveMorph(relation string, types []interface{}, args ...interface{}) orm.Query {
	var _ca []interface{}
	_ca = append(_ca, relation, types)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for WhereDoesntHaveMorph")
	}

	var r0 orm.Query
	if rf, ok := ret.Get(0).(func(string, []interface{}, ...interface{}) orm.Query); ok {
		r0 = rf(relation, types, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(orm.Query)
		}
	}

	return r0
}

// QueryWithRelations_WhereDoesntHaveMorph_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WhereDoesntHaveMorph'
type QueryWithRelations_WhereDoesntHaveMorph_Call struct {
	*mock.Call
}

// WhereDoesntHaveMorph is a helper method to define mock.On call
//   - relation string
//   - types []interface{}
//   - args ...interface{}
func (_e *QueryWithRelations_Expecter) WhereDoesntHaveMorph(relation interface{}, types interface{}, args ...interface{}) *QueryWithRelations_WhereDoesntHaveMorph_Call {
	return &QueryWithRelations_WhereDoesntHaveMorph_Call{Call: _e.mock.On("WhereDoesntHaveMorph",
		append([]interface{}{relation, types}, args...)...)}
}

func (_c *QueryWithRelations_WhereDoesntHaveMorph_Call) Run(run func(relation string, types []interface{}, args ...interface{})) *QueryWithRelations_WhereDoesntHaveMorph_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), args[1].([]interface{}), variadicArgs...)
	})
	return _c
}

func (_c *QueryWithRelations_WhereDoesntHaveMorph_Call) Return(_a0 orm.Query) *QueryWithRelations_WhereDoesntHaveMorph_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryWithRelations_WhereDoesntHaveMorph_Call) RunAndReturn(run func(string, []interface{}, ...interface{}) orm.Query) *QueryWithRelations_WhereDoesntHaveMorph_Call {
	_c.Call.Return(run)
	return _c
}

// WhereHas provides a mock function with given fields: relation, args
func (_m *QueryWithRelations) WhereHas(relation string, args ...interface{}) orm.Query {
	var _ca []interface{}
	_ca = append(_ca, relation)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for WhereHas")
	}

	var r0 orm.Query
	if rf, ok := ret.Get(0).(func(string, ...interface{}) orm.Query); ok {
		r0 = rf(relation, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(orm.Query)
		}
	}

	return r0
}

// QueryWithRelations_WhereHas_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WhereHas'
type QueryWithRelations_WhereHas_Call struct {
	*mock.Call
}

// WhereHas is a helper method to define mock.On call
//   - relation string
//   - args ...interface{}
func (_e *QueryWithRelations_Expecter) WhereHas(relation interface{}, args ...interface{}) *QueryWithRelations_WhereHas_Call {
	return &QueryWithRelations_WhereHas_Call{Call: _e.mock.On("WhereHas",
		append([]interface{}{relation}, args...)...)}
}

func (_c *QueryWithRelations_WhereHas_Call) Run(run func(relation string, args ...interface{})) *QueryWithRelations_WhereHas_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *QueryWithRelations_WhereHas_Call) Return(_a0 orm.Query) *QueryWithRelations_WhereHas_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryWithRelations_WhereHas_Call) RunAndReturn(run func(string, ...interface{}) orm.Query) *QueryWithRelations_WhereHas_Call {
	_c.Call.Return(run)
	return _c
}

// WhereHasMorph provides a mock function with given fields: relation, types, args
func (_m *QueryWithRelations) WhereHasMorph(relation string, types []interface{}, args ...interface{}) orm.Query {
	var _ca []interface{}
	_ca = append(_ca, relation, types)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for WhereHasMorph")
	}

	var r0 orm.Query
	if rf, ok := ret.Get(0).(func(string, []interface{}, ...interface{}) orm.Query); ok {
		r0 = rf(relation, types, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(orm.Query)
		}
	}

	return r0
}

// QueryWithRelations_WhereHasMorph_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WhereHasMorph'
type QueryWithRelations_WhereHasMorph_Call struct {
	*mock.Call
}

// WhereHasMorph is a helper method to define mock.On call
//   - relation string
//   - types []interface{}
//   - args ...interface{}
func (_e *QueryWithRelations_Expecter) WhereHasMorph(relation interface{}, types interface{}, args ...interface{}) *QueryWithRelations_WhereHasMorph_Call {
	return &QueryWithRelations_WhereHasMorph_Call{Call: _e.mock.On("WhereHasMorph",
		append([]interface{}{relation, types}, args...)...)}
}

func (_c *QueryWithRelations_WhereHasMorph_Call) Run(run func(relation string, types []interface{}, args ...interface{})) *QueryWithRelations_WhereHasMorph_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), args[1].([]interface{}), variadicArgs...)
	})
	return _c
}

func (_c *QueryWithRelations_WhereHasMorph_Call) Return(_a0 orm.Query) *QueryWithRelations_WhereHasMorph_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryWithRelations_WhereHasMorph_Call) RunAndReturn(run func(string, []interface{}, ...interface{}) orm.Query) *QueryWithRelations_WhereHasMorph_Call {
	_c.Call.Return(run)
	return _c
}

// WithAggregate provides a mock function with given fields: relation, column, fn, args
func (_m *QueryWithRelations) WithAggregate(relation string, column string, fn string, args ...interface{}) orm.Query {
	var _ca []interface{}
	_ca = append(_ca, relation, column, fn)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for WithAggregate")
	}

	var r0 orm.Query
	if rf, ok := ret.Get(0).(func(string, string, string, ...interface{}) orm.Query); ok {
		r0 = rf(relation, column, fn, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(orm.Query)
		}
	}

	return r0
}

// QueryWithRelations_WithAggregate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithAggregate'
type QueryWithRelations_WithAggregate_Call struct {
	*mock.Call
}

// WithAggregate is a helper method to define mock.On call
//   - relation string
//   - column string
//   - fn string
//   - args ...interface{}
func (_e *QueryWithRelations_Expecter) WithAggregate(relation interface{}, column interface{}, fn interface{}, args ...interface{}) *QueryWithRelations_WithAggregate_Call {
	return &QueryWithRelations_WithAggregate_Call{Call: _e.mock.On("WithAggregate",
		append([]interface{}{relation, column, fn}, args...)...)}
}

func (_c *QueryWithRelations_WithAggregate_Call) Run(run func(relation string, column string, fn string, args ...interface{})) *QueryWithRelations_WithAggregate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), args[1].(string), args[2].(string), variadicArgs...)
	})
	return _c
}

func (_c *QueryWithRelations_WithAggregate_Call) Return(_a0 orm.Query) *QueryWithRelations_WithAggregate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryWithRelations_WithAggregate_Call) RunAndReturn(run func(string, string, string, ...interface{}) orm.Query) *QueryWithRelations_WithAggregate_Call {
	_c.Call.Return(run)
	return _c
}

// WithAvg provides a mock function with given fields: relation, column, args
func (_m *QueryWithRelations) WithAvg(relation string, column string, args ...interface{}) orm.Query {
	var _ca []interface{}
	_ca = append(_ca, relation, column)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for WithAvg")
	}

	var r0 orm.Query
	if rf, ok := ret.Get(0).(func(string, string, ...interface{}) orm.Query); ok {
		r0 = rf(relation, column, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(orm.Query)
		}
	}

	return r0
}

// QueryWithRelations_WithAvg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithAvg'
type QueryWithRelations_WithAvg_Call struct {
	*mock.Call
}

// WithAvg is a helper method to define mock.On call
//   - relation string
//   - column string
//   - args ...interface{}
func (_e *QueryWithRelations_Expecter) WithAvg(relation interface{}, column interface{}, args ...interface{}) *QueryWithRelations_WithAvg_Call {
	return &QueryWithRelations_WithAvg_Call{Call: _e.mock.On("WithAvg",
		append([]interface{}{relation, column}, args...)...)}
}

func (_c *QueryWithRelations_WithAvg_Call) Run(run func(relation string, column string, args ...interface{})) *QueryWithRelations_WithAvg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *QueryWithRelations_WithAvg_Call) Return(_a0 orm.Query) *QueryWithRelations_WithAvg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryWithRelations_WithAvg_Call) RunAndReturn(run func(string, string, ...interface{}) orm.Query) *QueryWithRelations_WithAvg_Call {
	_c.Call.Return(run)
	return _c
}

// WithCount provides a mock function with given fields: relations
func (_m *QueryWithRelations) WithCount(relations ...interface{}) orm.Query {
	var _ca []interface{}
	_ca = append(_ca, relations...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for WithCount")
	}

	var r0 orm.Query
	if rf, ok := ret.Get(0).(func(...interface{}) orm.Query); ok {
		r0 = rf(relations...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(orm.Query)
		}
	}

	return r0
}

// QueryWithRelations_WithCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithCount'
type QueryWithRelations_WithCount_Call struct {
	*mock.Call
}

// WithCount is a helper method to define mock.On call
//   - relations ...interface{}
func (_e *QueryWithRelations_Expecter) WithCount(relations ...interface{}) *QueryWithRelations_WithCount_Call {
	return &QueryWithRelations_WithCount_Call{Call: _e.mock.On("WithCount",
		append([]interface{}{}, relations...)...)}
}

func (_c *QueryWithRelations_WithCount_Call) Run(run func(relations ...interface{})) *QueryWithRelations_WithCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *QueryWithRelations_WithCount_Call) Return(_a0 orm.Query) *QueryWithRelations_WithCount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryWithRelations_WithCount_Call) RunAndReturn(run func(...interface{}) orm.Query) *QueryWithRelations_WithCount_Call {
	_c.Call.Return(run)
	return _c
}

// WithExists provides a mock function with given fields: relations
func (_m *QueryWithRelations) WithExists(relations ...string) orm.Query {
	_va := make([]interface{}, len(relations))
	for _i := range relations {
		_va[_i] = relations[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for WithExists")
	}

	var r0 orm.Query
	if rf, ok := ret.Get(0).(func(...string) orm.Query); ok {
		r0 = rf(relations...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(orm.Query)
		}
	}

	return r0
}

// QueryWithRelations_WithExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithExists'
type QueryWithRelations_WithExists_Call struct {
	*mock.Call
}

// WithExists is a helper method to define mock.On call
//   - relations ...string
func (_e *QueryWithRelations_Expecter) WithExists(relations ...interface{}) *QueryWithRelations_WithExists_Call {
	return &QueryWithRelations_WithExists_Call{Call: _e.mock.On("WithExists",
		append([]interface{}{}, relations...)...)}
}

func (_c *QueryWithRelations_WithExists_Call) Run(run func(relations ...string)) *QueryWithRelations_WithExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *QueryWithRelations_WithExists_Call) Return(_a0 orm.Query) *QueryWithRelations_WithExists_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryWithRelations_WithExists_Call) RunAndReturn(run func(...string) orm.Query) *QueryWithRelations_WithExists_Call {
	_c.Call.Return(run)
	return _c
}

// WithMax provides a mock function with given fields: relation, column, args
func (_m *QueryWithRelations) WithMax(relation string, column string, args ...interface{}) orm.Query {
	var _ca []interface{}
	_ca = append(_ca, relation, column)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for WithMax")
	}

	var r0 orm.Query
	if rf, ok := ret.Get(0).(func(string, string, ...interface{}) orm.Query); ok {
		r0 = rf(relation, column, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(orm.Query)
		}
	}

	return r0
}

// QueryWithRelations_WithMax_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithMax'
type QueryWithRelations_WithMax_Call struct {
	*mock.Call
}

// WithMax is a helper method to define mock.On call
//   - relation string
//   - column string
//   - args ...interface{}
func (_e *QueryWithRelations_Expecter) WithMax(relation interface{}, column interface{}, args ...interface{}) *QueryWithRelations_WithMax_Call {
	return &QueryWithRelations_WithMax_Call{Call: _e.mock.On("WithMax",
		append([]interface{}{relation, column}, args...)...)}
}

func (_c *QueryWithRelations_WithMax_Call) Run(run func(relation string, column string, args ...interface{})) *QueryWithRelations_WithMax_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *QueryWithRelations_WithMax_Call) Return(_a0 orm.Query) *QueryWithRelations_WithMax_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryWithRelations_WithMax_Call) RunAndReturn(run func(string, string, ...interface{}) orm.Query) *QueryWithRelations_WithMax_Call {
	_c.Call.Return(run)
	return _c
}

// WithMin provides a mock function with given fields: relation, column, args
func (_m *QueryWithRelations) WithMin(relation string, column string, args ...interface{}) orm.Query {
	var _ca []interface{}
	_ca = append(_ca, relation, column)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for WithMin")
	}

	var r0 orm.Query
	if rf, ok := ret.Get(0).(func(string, string, ...interface{}) orm.Query); ok {
		r0 = rf(relation, column, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(orm.Query)
		}
	}

	return r0
}

// QueryWithRelations_WithMin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithMin'
type QueryWithRelations_WithMin_Call struct {
	*mock.Call
}

// WithMin is a helper method to define mock.On call
//   - relation string
//   - column string
//   - args ...interface{}
func (_e *QueryWithRelations_Expecter) WithMin(relation interface{}, column interface{}, args ...interface{}) *QueryWithRelations_WithMin_Call {
	return &QueryWithRelations_WithMin_Call{Call: _e.mock.On("WithMin",
		append([]interface{}{relation, column}, args...)...)}
}

func (_c *QueryWithRelations_WithMin_Call) Run(run func(relation string, column string, args ...interface{})) *QueryWithRelations_WithMin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *QueryWithRelations_WithMin_Call) Return(_a0 orm.Query) *QueryWithRelations_WithMin_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryWithRelations_WithMin_Call) RunAndReturn(run func(string, string, ...interface{}) orm.Query) *QueryWithRelations_WithMin_Call {
	_c.Call.Return(run)
	return _c
}

// WithSum provides a mock function with given fields: relation, column, args
func (_m *QueryWithRelations) WithSum(relation string, column string, args ...interface{}) orm.Query {
	var _ca []interface{}
	_ca = append(_ca, relation, column)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for WithSum")
	}

	var r0 orm.Query
	if rf, ok := ret.Get(0).(func(string, string, ...interface{}) orm.Query); ok {
		r0 = rf(relation, column, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(orm.Query)
		}
	}

	return r0
}

// QueryWithRelations_WithSum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithSum'
type QueryWithRelations_WithSum_Call struct {
	*mock.Call
}

// WithSum is a helper method to define mock.On call
//   - relation string
//   - column string
//   - args ...interface{}
func (_e *QueryWithRelations_Expecter) WithSum(relation interface{}, column interface{}, args ...interface{}) *QueryWithRelations_WithSum_Call {
	return &QueryWithRelations_WithSum_Call{Call: _e.mock.On("WithSum",
		append([]interface{}{relation, column}, args...)...)}
}

func (_c *QueryWithRelations_WithSum_Call) Run(run func(relation string, column string, args ...interface{})) *QueryWithRelations_WithSum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *QueryWithRelations_WithSum_Call) Return(_a0 orm.Query) *QueryWithRelations_WithSum_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueryWithRelations_WithSum_Call) RunAndReturn(run func(string, string, ...interface{}) orm.Query) *QueryWithRelations_WithSum_Call {
	_c.Call.Return(run)
	return _c
}

// NewQueryWithRelations creates a new instance of QueryWithRelations. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueryWithRelations(t interface {
	mock.TestingT
	Cleanup(func())
}) *QueryWithRelations {
	mock := &QueryWithRelations{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
