// Code generated by mockery. DO NOT EDIT.

package orm

import (
	db "github.com/goravel/framework/contracts/database/db"
	mock "github.com/stretchr/testify/mock"
)

// RelationWriter is an autogenerated mock type for the RelationWriter type
type RelationWriter struct {
	mock.Mock
}

type RelationWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *RelationWriter) EXPECT() *RelationWriter_Expecter {
	return &RelationWriter_Expecter{mock: &_m.Mock}
}

// Associate provides a mock function with given fields: owner
func (_m *RelationWriter) Associate(owner interface{}) error {
	ret := _m.Called(owner)

	if len(ret) == 0 {
		panic("no return value specified for Associate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(owner)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RelationWriter_Associate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Associate'
type RelationWriter_Associate_Call struct {
	*mock.Call
}

// Associate is a helper method to define mock.On call
//   - owner interface{}
func (_e *RelationWriter_Expecter) Associate(owner interface{}) *RelationWriter_Associate_Call {
	return &RelationWriter_Associate_Call{Call: _e.mock.On("Associate", owner)}
}

func (_c *RelationWriter_Associate_Call) Run(run func(owner interface{})) *RelationWriter_Associate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *RelationWriter_Associate_Call) Return(_a0 error) *RelationWriter_Associate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RelationWriter_Associate_Call) RunAndReturn(run func(interface{}) error) *RelationWriter_Associate_Call {
	_c.Call.Return(run)
	return _c
}

// Attach provides a mock function with given fields: ids
func (_m *RelationWriter) Attach(ids []interface{}) error {
	ret := _m.Called(ids)

	if len(ret) == 0 {
		panic("no return value specified for Attach")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]interface{}) error); ok {
		r0 = rf(ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RelationWriter_Attach_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Attach'
type RelationWriter_Attach_Call struct {
	*mock.Call
}

// Attach is a helper method to define mock.On call
//   - ids []interface{}
func (_e *RelationWriter_Expecter) Attach(ids interface{}) *RelationWriter_Attach_Call {
	return &RelationWriter_Attach_Call{Call: _e.mock.On("Attach", ids)}
}

func (_c *RelationWriter_Attach_Call) Run(run func(ids []interface{})) *RelationWriter_Attach_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]interface{}))
	})
	return _c
}

func (_c *RelationWriter_Attach_Call) Return(_a0 error) *RelationWriter_Attach_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RelationWriter_Attach_Call) RunAndReturn(run func([]interface{}) error) *RelationWriter_Attach_Call {
	_c.Call.Return(run)
	return _c
}

// AttachWithPivot provides a mock function with given fields: idsWithAttrs
func (_m *RelationWriter) AttachWithPivot(idsWithAttrs map[interface{}]map[string]interface{}) error {
	ret := _m.Called(idsWithAttrs)

	if len(ret) == 0 {
		panic("no return value specified for AttachWithPivot")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(map[interface{}]map[string]interface{}) error); ok {
		r0 = rf(idsWithAttrs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RelationWriter_AttachWithPivot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachWithPivot'
type RelationWriter_AttachWithPivot_Call struct {
	*mock.Call
}

// AttachWithPivot is a helper method to define mock.On call
//   - idsWithAttrs map[interface{}]map[string]interface{}
func (_e *RelationWriter_Expecter) AttachWithPivot(idsWithAttrs interface{}) *RelationWriter_AttachWithPivot_Call {
	return &RelationWriter_AttachWithPivot_Call{Call: _e.mock.On("AttachWithPivot", idsWithAttrs)}
}

func (_c *RelationWriter_AttachWithPivot_Call) Run(run func(idsWithAttrs map[interface{}]map[string]interface{})) *RelationWriter_AttachWithPivot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[interface{}]map[string]interface{}))
	})
	return _c
}

func (_c *RelationWriter_AttachWithPivot_Call) Return(_a0 error) *RelationWriter_AttachWithPivot_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RelationWriter_AttachWithPivot_Call) RunAndReturn(run func(map[interface{}]map[string]interface{}) error) *RelationWriter_AttachWithPivot_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: dest
func (_m *RelationWriter) Create(dest interface{}) error {
	ret := _m.Called(dest)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(dest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RelationWriter_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type RelationWriter_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - dest interface{}
func (_e *RelationWriter_Expecter) Create(dest interface{}) *RelationWriter_Create_Call {
	return &RelationWriter_Create_Call{Call: _e.mock.On("Create", dest)}
}

func (_c *RelationWriter_Create_Call) Run(run func(dest interface{})) *RelationWriter_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *RelationWriter_Create_Call) Return(_a0 error) *RelationWriter_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RelationWriter_Create_Call) RunAndReturn(run func(interface{}) error) *RelationWriter_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMany provides a mock function with given fields: dests
func (_m *RelationWriter) CreateMany(dests interface{}) error {
	ret := _m.Called(dests)

	if len(ret) == 0 {
		panic("no return value specified for CreateMany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(dests)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RelationWriter_CreateMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMany'
type RelationWriter_CreateMany_Call struct {
	*mock.Call
}

// CreateMany is a helper method to define mock.On call
//   - dests interface{}
func (_e *RelationWriter_Expecter) CreateMany(dests interface{}) *RelationWriter_CreateMany_Call {
	return &RelationWriter_CreateMany_Call{Call: _e.mock.On("CreateMany", dests)}
}

func (_c *RelationWriter_CreateMany_Call) Run(run func(dests interface{})) *RelationWriter_CreateMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *RelationWriter_CreateMany_Call) Return(_a0 error) *RelationWriter_CreateMany_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RelationWriter_CreateMany_Call) RunAndReturn(run func(interface{}) error) *RelationWriter_CreateMany_Call {
	_c.Call.Return(run)
	return _c
}

// Detach provides a mock function with given fields: ids
func (_m *RelationWriter) Detach(ids ...interface{}) (int64, error) {
	var _ca []interface{}
	_ca = append(_ca, ids...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Detach")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(...interface{}) (int64, error)); ok {
		return rf(ids...)
	}
	if rf, ok := ret.Get(0).(func(...interface{}) int64); ok {
		r0 = rf(ids...)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(...interface{}) error); ok {
		r1 = rf(ids...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RelationWriter_Detach_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Detach'
type RelationWriter_Detach_Call struct {
	*mock.Call
}

// Detach is a helper method to define mock.On call
//   - ids ...interface{}
func (_e *RelationWriter_Expecter) Detach(ids ...interface{}) *RelationWriter_Detach_Call {
	return &RelationWriter_Detach_Call{Call: _e.mock.On("Detach",
		append([]interface{}{}, ids...)...)}
}

func (_c *RelationWriter_Detach_Call) Run(run func(ids ...interface{})) *RelationWriter_Detach_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *RelationWriter_Detach_Call) Return(_a0 int64, _a1 error) *RelationWriter_Detach_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RelationWriter_Detach_Call) RunAndReturn(run func(...interface{}) (int64, error)) *RelationWriter_Detach_Call {
	_c.Call.Return(run)
	return _c
}

// Dissociate provides a mock function with no fields
func (_m *RelationWriter) Dissociate() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Dissociate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RelationWriter_Dissociate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dissociate'
type RelationWriter_Dissociate_Call struct {
	*mock.Call
}

// Dissociate is a helper method to define mock.On call
func (_e *RelationWriter_Expecter) Dissociate() *RelationWriter_Dissociate_Call {
	return &RelationWriter_Dissociate_Call{Call: _e.mock.On("Dissociate")}
}

func (_c *RelationWriter_Dissociate_Call) Run(run func()) *RelationWriter_Dissociate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RelationWriter_Dissociate_Call) Return(_a0 error) *RelationWriter_Dissociate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RelationWriter_Dissociate_Call) RunAndReturn(run func() error) *RelationWriter_Dissociate_Call {
	_c.Call.Return(run)
	return _c
}

// FindOrNew provides a mock function with given fields: id, dest
func (_m *RelationWriter) FindOrNew(id interface{}, dest interface{}) error {
	ret := _m.Called(id, dest)

	if len(ret) == 0 {
		panic("no return value specified for FindOrNew")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, interface{}) error); ok {
		r0 = rf(id, dest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RelationWriter_FindOrNew_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOrNew'
type RelationWriter_FindOrNew_Call struct {
	*mock.Call
}

// FindOrNew is a helper method to define mock.On call
//   - id interface{}
//   - dest interface{}
func (_e *RelationWriter_Expecter) FindOrNew(id interface{}, dest interface{}) *RelationWriter_FindOrNew_Call {
	return &RelationWriter_FindOrNew_Call{Call: _e.mock.On("FindOrNew", id, dest)}
}

func (_c *RelationWriter_FindOrNew_Call) Run(run func(id interface{}, dest interface{})) *RelationWriter_FindOrNew_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].(interface{}))
	})
	return _c
}

func (_c *RelationWriter_FindOrNew_Call) Return(_a0 error) *RelationWriter_FindOrNew_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RelationWriter_FindOrNew_Call) RunAndReturn(run func(interface{}, interface{}) error) *RelationWriter_FindOrNew_Call {
	_c.Call.Return(run)
	return _c
}

// FirstOrCreate provides a mock function with given fields: attrs, values, dest
func (_m *RelationWriter) FirstOrCreate(attrs map[string]interface{}, values map[string]interface{}, dest interface{}) error {
	ret := _m.Called(attrs, values, dest)

	if len(ret) == 0 {
		panic("no return value specified for FirstOrCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]interface{}, map[string]interface{}, interface{}) error); ok {
		r0 = rf(attrs, values, dest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RelationWriter_FirstOrCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FirstOrCreate'
type RelationWriter_FirstOrCreate_Call struct {
	*mock.Call
}

// FirstOrCreate is a helper method to define mock.On call
//   - attrs map[string]interface{}
//   - values map[string]interface{}
//   - dest interface{}
func (_e *RelationWriter_Expecter) FirstOrCreate(attrs interface{}, values interface{}, dest interface{}) *RelationWriter_FirstOrCreate_Call {
	return &RelationWriter_FirstOrCreate_Call{Call: _e.mock.On("FirstOrCreate", attrs, values, dest)}
}

func (_c *RelationWriter_FirstOrCreate_Call) Run(run func(attrs map[string]interface{}, values map[string]interface{}, dest interface{})) *RelationWriter_FirstOrCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string]interface{}), args[1].(map[string]interface{}), args[2].(interface{}))
	})
	return _c
}

func (_c *RelationWriter_FirstOrCreate_Call) Return(_a0 error) *RelationWriter_FirstOrCreate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RelationWriter_FirstOrCreate_Call) RunAndReturn(run func(map[string]interface{}, map[string]interface{}, interface{}) error) *RelationWriter_FirstOrCreate_Call {
	_c.Call.Return(run)
	return _c
}

// FirstOrNew provides a mock function with given fields: attrs, values, dest
func (_m *RelationWriter) FirstOrNew(attrs map[string]interface{}, values map[string]interface{}, dest interface{}) error {
	ret := _m.Called(attrs, values, dest)

	if len(ret) == 0 {
		panic("no return value specified for FirstOrNew")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]interface{}, map[string]interface{}, interface{}) error); ok {
		r0 = rf(attrs, values, dest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RelationWriter_FirstOrNew_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FirstOrNew'
type RelationWriter_FirstOrNew_Call struct {
	*mock.Call
}

// FirstOrNew is a helper method to define mock.On call
//   - attrs map[string]interface{}
//   - values map[string]interface{}
//   - dest interface{}
func (_e *RelationWriter_Expecter) FirstOrNew(attrs interface{}, values interface{}, dest interface{}) *RelationWriter_FirstOrNew_Call {
	return &RelationWriter_FirstOrNew_Call{Call: _e.mock.On("FirstOrNew", attrs, values, dest)}
}

func (_c *RelationWriter_FirstOrNew_Call) Run(run func(attrs map[string]interface{}, values map[string]interface{}, dest interface{})) *RelationWriter_FirstOrNew_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string]interface{}), args[1].(map[string]interface{}), args[2].(interface{}))
	})
	return _c
}

func (_c *RelationWriter_FirstOrNew_Call) Return(_a0 error) *RelationWriter_FirstOrNew_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RelationWriter_FirstOrNew_Call) RunAndReturn(run func(map[string]interface{}, map[string]interface{}, interface{}) error) *RelationWriter_FirstOrNew_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: child
func (_m *RelationWriter) Save(child interface{}) error {
	ret := _m.Called(child)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(child)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RelationWriter_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type RelationWriter_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - child interface{}
func (_e *RelationWriter_Expecter) Save(child interface{}) *RelationWriter_Save_Call {
	return &RelationWriter_Save_Call{Call: _e.mock.On("Save", child)}
}

func (_c *RelationWriter_Save_Call) Run(run func(child interface{})) *RelationWriter_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *RelationWriter_Save_Call) Return(_a0 error) *RelationWriter_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RelationWriter_Save_Call) RunAndReturn(run func(interface{}) error) *RelationWriter_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SaveMany provides a mock function with given fields: children
func (_m *RelationWriter) SaveMany(children interface{}) error {
	ret := _m.Called(children)

	if len(ret) == 0 {
		panic("no return value specified for SaveMany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(children)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RelationWriter_SaveMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveMany'
type RelationWriter_SaveMany_Call struct {
	*mock.Call
}

// SaveMany is a helper method to define mock.On call
//   - children interface{}
func (_e *RelationWriter_Expecter) SaveMany(children interface{}) *RelationWriter_SaveMany_Call {
	return &RelationWriter_SaveMany_Call{Call: _e.mock.On("SaveMany", children)}
}

func (_c *RelationWriter_SaveMany_Call) Run(run func(children interface{})) *RelationWriter_SaveMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *RelationWriter_SaveMany_Call) Return(_a0 error) *RelationWriter_SaveMany_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RelationWriter_SaveMany_Call) RunAndReturn(run func(interface{}) error) *RelationWriter_SaveMany_Call {
	_c.Call.Return(run)
	return _c
}

// SaveManyWithPivot provides a mock function with given fields: children, attrsPerChild
func (_m *RelationWriter) SaveManyWithPivot(children interface{}, attrsPerChild map[interface{}]map[string]interface{}) error {
	ret := _m.Called(children, attrsPerChild)

	if len(ret) == 0 {
		panic("no return value specified for SaveManyWithPivot")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, map[interface{}]map[string]interface{}) error); ok {
		r0 = rf(children, attrsPerChild)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RelationWriter_SaveManyWithPivot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveManyWithPivot'
type RelationWriter_SaveManyWithPivot_Call struct {
	*mock.Call
}

// SaveManyWithPivot is a helper method to define mock.On call
//   - children interface{}
//   - attrsPerChild map[interface{}]map[string]interface{}
func (_e *RelationWriter_Expecter) SaveManyWithPivot(children interface{}, attrsPerChild interface{}) *RelationWriter_SaveManyWithPivot_Call {
	return &RelationWriter_SaveManyWithPivot_Call{Call: _e.mock.On("SaveManyWithPivot", children, attrsPerChild)}
}

func (_c *RelationWriter_SaveManyWithPivot_Call) Run(run func(children interface{}, attrsPerChild map[interface{}]map[string]interface{})) *RelationWriter_SaveManyWithPivot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].(map[interface{}]map[string]interface{}))
	})
	return _c
}

func (_c *RelationWriter_SaveManyWithPivot_Call) Return(_a0 error) *RelationWriter_SaveManyWithPivot_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RelationWriter_SaveManyWithPivot_Call) RunAndReturn(run func(interface{}, map[interface{}]map[string]interface{}) error) *RelationWriter_SaveManyWithPivot_Call {
	_c.Call.Return(run)
	return _c
}

// SaveWithPivot provides a mock function with given fields: child, attrs
func (_m *RelationWriter) SaveWithPivot(child interface{}, attrs map[string]interface{}) error {
	ret := _m.Called(child, attrs)

	if len(ret) == 0 {
		panic("no return value specified for SaveWithPivot")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, map[string]interface{}) error); ok {
		r0 = rf(child, attrs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RelationWriter_SaveWithPivot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveWithPivot'
type RelationWriter_SaveWithPivot_Call struct {
	*mock.Call
}

// SaveWithPivot is a helper method to define mock.On call
//   - child interface{}
//   - attrs map[string]interface{}
func (_e *RelationWriter_Expecter) SaveWithPivot(child interface{}, attrs interface{}) *RelationWriter_SaveWithPivot_Call {
	return &RelationWriter_SaveWithPivot_Call{Call: _e.mock.On("SaveWithPivot", child, attrs)}
}

func (_c *RelationWriter_SaveWithPivot_Call) Run(run func(child interface{}, attrs map[string]interface{})) *RelationWriter_SaveWithPivot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].(map[string]interface{}))
	})
	return _c
}

func (_c *RelationWriter_SaveWithPivot_Call) Return(_a0 error) *RelationWriter_SaveWithPivot_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RelationWriter_SaveWithPivot_Call) RunAndReturn(run func(interface{}, map[string]interface{}) error) *RelationWriter_SaveWithPivot_Call {
	_c.Call.Return(run)
	return _c
}

// Sync provides a mock function with given fields: ids
func (_m *RelationWriter) Sync(ids []interface{}) (*db.SyncResult, error) {
	ret := _m.Called(ids)

	if len(ret) == 0 {
		panic("no return value specified for Sync")
	}

	var r0 *db.SyncResult
	var r1 error
	if rf, ok := ret.Get(0).(func([]interface{}) (*db.SyncResult, error)); ok {
		return rf(ids)
	}
	if rf, ok := ret.Get(0).(func([]interface{}) *db.SyncResult); ok {
		r0 = rf(ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.SyncResult)
		}
	}

	if rf, ok := ret.Get(1).(func([]interface{}) error); ok {
		r1 = rf(ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RelationWriter_Sync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sync'
type RelationWriter_Sync_Call struct {
	*mock.Call
}

// Sync is a helper method to define mock.On call
//   - ids []interface{}
func (_e *RelationWriter_Expecter) Sync(ids interface{}) *RelationWriter_Sync_Call {
	return &RelationWriter_Sync_Call{Call: _e.mock.On("Sync", ids)}
}

func (_c *RelationWriter_Sync_Call) Run(run func(ids []interface{})) *RelationWriter_Sync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]interface{}))
	})
	return _c
}

func (_c *RelationWriter_Sync_Call) Return(_a0 *db.SyncResult, _a1 error) *RelationWriter_Sync_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RelationWriter_Sync_Call) RunAndReturn(run func([]interface{}) (*db.SyncResult, error)) *RelationWriter_Sync_Call {
	_c.Call.Return(run)
	return _c
}

// SyncWithPivot provides a mock function with given fields: idsWithAttrs
func (_m *RelationWriter) SyncWithPivot(idsWithAttrs map[interface{}]map[string]interface{}) (*db.SyncResult, error) {
	ret := _m.Called(idsWithAttrs)

	if len(ret) == 0 {
		panic("no return value specified for SyncWithPivot")
	}

	var r0 *db.SyncResult
	var r1 error
	if rf, ok := ret.Get(0).(func(map[interface{}]map[string]interface{}) (*db.SyncResult, error)); ok {
		return rf(idsWithAttrs)
	}
	if rf, ok := ret.Get(0).(func(map[interface{}]map[string]interface{}) *db.SyncResult); ok {
		r0 = rf(idsWithAttrs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.SyncResult)
		}
	}

	if rf, ok := ret.Get(1).(func(map[interface{}]map[string]interface{}) error); ok {
		r1 = rf(idsWithAttrs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RelationWriter_SyncWithPivot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncWithPivot'
type RelationWriter_SyncWithPivot_Call struct {
	*mock.Call
}

// SyncWithPivot is a helper method to define mock.On call
//   - idsWithAttrs map[interface{}]map[string]interface{}
func (_e *RelationWriter_Expecter) SyncWithPivot(idsWithAttrs interface{}) *RelationWriter_SyncWithPivot_Call {
	return &RelationWriter_SyncWithPivot_Call{Call: _e.mock.On("SyncWithPivot", idsWithAttrs)}
}

func (_c *RelationWriter_SyncWithPivot_Call) Run(run func(idsWithAttrs map[interface{}]map[string]interface{})) *RelationWriter_SyncWithPivot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[interface{}]map[string]interface{}))
	})
	return _c
}

func (_c *RelationWriter_SyncWithPivot_Call) Return(_a0 *db.SyncResult, _a1 error) *RelationWriter_SyncWithPivot_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RelationWriter_SyncWithPivot_Call) RunAndReturn(run func(map[interface{}]map[string]interface{}) (*db.SyncResult, error)) *RelationWriter_SyncWithPivot_Call {
	_c.Call.Return(run)
	return _c
}

// SyncWithPivotValues provides a mock function with given fields: ids, pivotValues
func (_m *RelationWriter) SyncWithPivotValues(ids []interface{}, pivotValues map[string]interface{}) (*db.SyncResult, error) {
	ret := _m.Called(ids, pivotValues)

	if len(ret) == 0 {
		panic("no return value specified for SyncWithPivotValues")
	}

	var r0 *db.SyncResult
	var r1 error
	if rf, ok := ret.Get(0).(func([]interface{}, map[string]interface{}) (*db.SyncResult, error)); ok {
		return rf(ids, pivotValues)
	}
	if rf, ok := ret.Get(0).(func([]interface{}, map[string]interface{}) *db.SyncResult); ok {
		r0 = rf(ids, pivotValues)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.SyncResult)
		}
	}

	if rf, ok := ret.Get(1).(func([]interface{}, map[string]interface{}) error); ok {
		r1 = rf(ids, pivotValues)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RelationWriter_SyncWithPivotValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncWithPivotValues'
type RelationWriter_SyncWithPivotValues_Call struct {
	*mock.Call
}

// SyncWithPivotValues is a helper method to define mock.On call
//   - ids []interface{}
//   - pivotValues map[string]interface{}
func (_e *RelationWriter_Expecter) SyncWithPivotValues(ids interface{}, pivotValues interface{}) *RelationWriter_SyncWithPivotValues_Call {
	return &RelationWriter_SyncWithPivotValues_Call{Call: _e.mock.On("SyncWithPivotValues", ids, pivotValues)}
}

func (_c *RelationWriter_SyncWithPivotValues_Call) Run(run func(ids []interface{}, pivotValues map[string]interface{})) *RelationWriter_SyncWithPivotValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]interface{}), args[1].(map[string]interface{}))
	})
	return _c
}

func (_c *RelationWriter_SyncWithPivotValues_Call) Return(_a0 *db.SyncResult, _a1 error) *RelationWriter_SyncWithPivotValues_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RelationWriter_SyncWithPivotValues_Call) RunAndReturn(run func([]interface{}, map[string]interface{}) (*db.SyncResult, error)) *RelationWriter_SyncWithPivotValues_Call {
	_c.Call.Return(run)
	return _c
}

// SyncWithoutDetaching provides a mock function with given fields: ids
func (_m *RelationWriter) SyncWithoutDetaching(ids []interface{}) (*db.SyncResult, error) {
	ret := _m.Called(ids)

	if len(ret) == 0 {
		panic("no return value specified for SyncWithoutDetaching")
	}

	var r0 *db.SyncResult
	var r1 error
	if rf, ok := ret.Get(0).(func([]interface{}) (*db.SyncResult, error)); ok {
		return rf(ids)
	}
	if rf, ok := ret.Get(0).(func([]interface{}) *db.SyncResult); ok {
		r0 = rf(ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.SyncResult)
		}
	}

	if rf, ok := ret.Get(1).(func([]interface{}) error); ok {
		r1 = rf(ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RelationWriter_SyncWithoutDetaching_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncWithoutDetaching'
type RelationWriter_SyncWithoutDetaching_Call struct {
	*mock.Call
}

// SyncWithoutDetaching is a helper method to define mock.On call
//   - ids []interface{}
func (_e *RelationWriter_Expecter) SyncWithoutDetaching(ids interface{}) *RelationWriter_SyncWithoutDetaching_Call {
	return &RelationWriter_SyncWithoutDetaching_Call{Call: _e.mock.On("SyncWithoutDetaching", ids)}
}

func (_c *RelationWriter_SyncWithoutDetaching_Call) Run(run func(ids []interface{})) *RelationWriter_SyncWithoutDetaching_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]interface{}))
	})
	return _c
}

func (_c *RelationWriter_SyncWithoutDetaching_Call) Return(_a0 *db.SyncResult, _a1 error) *RelationWriter_SyncWithoutDetaching_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RelationWriter_SyncWithoutDetaching_Call) RunAndReturn(run func([]interface{}) (*db.SyncResult, error)) *RelationWriter_SyncWithoutDetaching_Call {
	_c.Call.Return(run)
	return _c
}

// SyncWithoutDetachingWithPivot provides a mock function with given fields: idsWithAttrs
func (_m *RelationWriter) SyncWithoutDetachingWithPivot(idsWithAttrs map[interface{}]map[string]interface{}) (*db.SyncResult, error) {
	ret := _m.Called(idsWithAttrs)

	if len(ret) == 0 {
		panic("no return value specified for SyncWithoutDetachingWithPivot")
	}

	var r0 *db.SyncResult
	var r1 error
	if rf, ok := ret.Get(0).(func(map[interface{}]map[string]interface{}) (*db.SyncResult, error)); ok {
		return rf(idsWithAttrs)
	}
	if rf, ok := ret.Get(0).(func(map[interface{}]map[string]interface{}) *db.SyncResult); ok {
		r0 = rf(idsWithAttrs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.SyncResult)
		}
	}

	if rf, ok := ret.Get(1).(func(map[interface{}]map[string]interface{}) error); ok {
		r1 = rf(idsWithAttrs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RelationWriter_SyncWithoutDetachingWithPivot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncWithoutDetachingWithPivot'
type RelationWriter_SyncWithoutDetachingWithPivot_Call struct {
	*mock.Call
}

// SyncWithoutDetachingWithPivot is a helper method to define mock.On call
//   - idsWithAttrs map[interface{}]map[string]interface{}
func (_e *RelationWriter_Expecter) SyncWithoutDetachingWithPivot(idsWithAttrs interface{}) *RelationWriter_SyncWithoutDetachingWithPivot_Call {
	return &RelationWriter_SyncWithoutDetachingWithPivot_Call{Call: _e.mock.On("SyncWithoutDetachingWithPivot", idsWithAttrs)}
}

func (_c *RelationWriter_SyncWithoutDetachingWithPivot_Call) Run(run func(idsWithAttrs map[interface{}]map[string]interface{})) *RelationWriter_SyncWithoutDetachingWithPivot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[interface{}]map[string]interface{}))
	})
	return _c
}

func (_c *RelationWriter_SyncWithoutDetachingWithPivot_Call) Return(_a0 *db.SyncResult, _a1 error) *RelationWriter_SyncWithoutDetachingWithPivot_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RelationWriter_SyncWithoutDetachingWithPivot_Call) RunAndReturn(run func(map[interface{}]map[string]interface{}) (*db.SyncResult, error)) *RelationWriter_SyncWithoutDetachingWithPivot_Call {
	_c.Call.Return(run)
	return _c
}

// Toggle provides a mock function with given fields: ids
func (_m *RelationWriter) Toggle(ids []interface{}) (*db.SyncResult, error) {
	ret := _m.Called(ids)

	if len(ret) == 0 {
		panic("no return value specified for Toggle")
	}

	var r0 *db.SyncResult
	var r1 error
	if rf, ok := ret.Get(0).(func([]interface{}) (*db.SyncResult, error)); ok {
		return rf(ids)
	}
	if rf, ok := ret.Get(0).(func([]interface{}) *db.SyncResult); ok {
		r0 = rf(ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.SyncResult)
		}
	}

	if rf, ok := ret.Get(1).(func([]interface{}) error); ok {
		r1 = rf(ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RelationWriter_Toggle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Toggle'
type RelationWriter_Toggle_Call struct {
	*mock.Call
}

// Toggle is a helper method to define mock.On call
//   - ids []interface{}
func (_e *RelationWriter_Expecter) Toggle(ids interface{}) *RelationWriter_Toggle_Call {
	return &RelationWriter_Toggle_Call{Call: _e.mock.On("Toggle", ids)}
}

func (_c *RelationWriter_Toggle_Call) Run(run func(ids []interface{})) *RelationWriter_Toggle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]interface{}))
	})
	return _c
}

func (_c *RelationWriter_Toggle_Call) Return(_a0 *db.SyncResult, _a1 error) *RelationWriter_Toggle_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RelationWriter_Toggle_Call) RunAndReturn(run func([]interface{}) (*db.SyncResult, error)) *RelationWriter_Toggle_Call {
	_c.Call.Return(run)
	return _c
}

// ToggleWithPivot provides a mock function with given fields: idsWithAttrs
func (_m *RelationWriter) ToggleWithPivot(idsWithAttrs map[interface{}]map[string]interface{}) (*db.SyncResult, error) {
	ret := _m.Called(idsWithAttrs)

	if len(ret) == 0 {
		panic("no return value specified for ToggleWithPivot")
	}

	var r0 *db.SyncResult
	var r1 error
	if rf, ok := ret.Get(0).(func(map[interface{}]map[string]interface{}) (*db.SyncResult, error)); ok {
		return rf(idsWithAttrs)
	}
	if rf, ok := ret.Get(0).(func(map[interface{}]map[string]interface{}) *db.SyncResult); ok {
		r0 = rf(idsWithAttrs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.SyncResult)
		}
	}

	if rf, ok := ret.Get(1).(func(map[interface{}]map[string]interface{}) error); ok {
		r1 = rf(idsWithAttrs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RelationWriter_ToggleWithPivot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToggleWithPivot'
type RelationWriter_ToggleWithPivot_Call struct {
	*mock.Call
}

// ToggleWithPivot is a helper method to define mock.On call
//   - idsWithAttrs map[interface{}]map[string]interface{}
func (_e *RelationWriter_Expecter) ToggleWithPivot(idsWithAttrs interface{}) *RelationWriter_ToggleWithPivot_Call {
	return &RelationWriter_ToggleWithPivot_Call{Call: _e.mock.On("ToggleWithPivot", idsWithAttrs)}
}

func (_c *RelationWriter_ToggleWithPivot_Call) Run(run func(idsWithAttrs map[interface{}]map[string]interface{})) *RelationWriter_ToggleWithPivot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[interface{}]map[string]interface{}))
	})
	return _c
}

func (_c *RelationWriter_ToggleWithPivot_Call) Return(_a0 *db.SyncResult, _a1 error) *RelationWriter_ToggleWithPivot_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RelationWriter_ToggleWithPivot_Call) RunAndReturn(run func(map[interface{}]map[string]interface{}) (*db.SyncResult, error)) *RelationWriter_ToggleWithPivot_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateExistingPivot provides a mock function with given fields: id, attrs
func (_m *RelationWriter) UpdateExistingPivot(id interface{}, attrs map[string]interface{}) (int64, error) {
	ret := _m.Called(id, attrs)

	if len(ret) == 0 {
		panic("no return value specified for UpdateExistingPivot")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}, map[string]interface{}) (int64, error)); ok {
		return rf(id, attrs)
	}
	if rf, ok := ret.Get(0).(func(interface{}, map[string]interface{}) int64); ok {
		r0 = rf(id, attrs)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(interface{}, map[string]interface{}) error); ok {
		r1 = rf(id, attrs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RelationWriter_UpdateExistingPivot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateExistingPivot'
type RelationWriter_UpdateExistingPivot_Call struct {
	*mock.Call
}

// UpdateExistingPivot is a helper method to define mock.On call
//   - id interface{}
//   - attrs map[string]interface{}
func (_e *RelationWriter_Expecter) UpdateExistingPivot(id interface{}, attrs interface{}) *RelationWriter_UpdateExistingPivot_Call {
	return &RelationWriter_UpdateExistingPivot_Call{Call: _e.mock.On("UpdateExistingPivot", id, attrs)}
}

func (_c *RelationWriter_UpdateExistingPivot_Call) Run(run func(id interface{}, attrs map[string]interface{})) *RelationWriter_UpdateExistingPivot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].(map[string]interface{}))
	})
	return _c
}

func (_c *RelationWriter_UpdateExistingPivot_Call) Return(_a0 int64, _a1 error) *RelationWriter_UpdateExistingPivot_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RelationWriter_UpdateExistingPivot_Call) RunAndReturn(run func(interface{}, map[string]interface{}) (int64, error)) *RelationWriter_UpdateExistingPivot_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrCreate provides a mock function with given fields: attrs, values, dest
func (_m *RelationWriter) UpdateOrCreate(attrs map[string]interface{}, values map[string]interface{}, dest interface{}) error {
	ret := _m.Called(attrs, values, dest)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]interface{}, map[string]interface{}, interface{}) error); ok {
		r0 = rf(attrs, values, dest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RelationWriter_UpdateOrCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrCreate'
type RelationWriter_UpdateOrCreate_Call struct {
	*mock.Call
}

// UpdateOrCreate is a helper method to define mock.On call
//   - attrs map[string]interface{}
//   - values map[string]interface{}
//   - dest interface{}
func (_e *RelationWriter_Expecter) UpdateOrCreate(attrs interface{}, values interface{}, dest interface{}) *RelationWriter_UpdateOrCreate_Call {
	return &RelationWriter_UpdateOrCreate_Call{Call: _e.mock.On("UpdateOrCreate", attrs, values, dest)}
}

func (_c *RelationWriter_UpdateOrCreate_Call) Run(run func(attrs map[string]interface{}, values map[string]interface{}, dest interface{})) *RelationWriter_UpdateOrCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string]interface{}), args[1].(map[string]interface{}), args[2].(interface{}))
	})
	return _c
}

func (_c *RelationWriter_UpdateOrCreate_Call) Return(_a0 error) *RelationWriter_UpdateOrCreate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RelationWriter_UpdateOrCreate_Call) RunAndReturn(run func(map[string]interface{}, map[string]interface{}, interface{}) error) *RelationWriter_UpdateOrCreate_Call {
	_c.Call.Return(run)
	return _c
}

// NewRelationWriter creates a new instance of RelationWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRelationWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *RelationWriter {
	mock := &RelationWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
