name: Test
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - 'mail/**'
env:
  MAIL_HOST: ${{ secrets.MAIL_HOST }}
  MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
  MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
  MAIL_FROM_ADDRESS: ${{ secrets.MAIL_FROM_ADDRESS }}
  MAIL_FROM_NAME: ${{ secrets.MAIL_FROM_NAME }}
  MAIL_TO: ${{ secrets.MAIL_TO }}
  MAIL_CC: ${{ secrets.MAIL_CC }}
  MAIL_BCC: ${{ secrets.MAIL_BCC }}
jobs:
  mail:
    strategy:
      matrix:
        go: [ '1.18' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Install dependencies
        run: go mod tidy
      - name: Run tests
        run: go test ./mail/...