name: Test External
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  ubuntu:
    strategy:
      matrix:
        go: [ "1.24", "1.25" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
      - name: Install dependencies
        run: go mod tidy && cd tests && go mod tidy
      - name: Run tests
        run: cd tests && go test -timeout 1h ./...
        
